### ISSUE TITLE
Pass BigQuery labels to created jobs

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#1009]
We allow setting labels on tables and views, we should also pass those labels to the jobs that we create when building tables.

https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfiguration

**Comment by BenBirt** [comment]
I don't think this is actually possible using the nodeJS client library right now. I have filed https://github.com/googleapis/nodejs-bigquery/issues/863 with a suggested fix and am happy to send it if they give me the go-ahead.

**Comment by BenBirt** [comment]
I've sent out https://github.com/googleapis/nodejs-bigquery/pull/865 on the BQ client lib.
