### ISSUE TITLE
pg-cursor uncaught exception: Cannot read property 'removeListener' of null

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#1010]
7-day logs: https://bit.ly/3kTYrBD

**Comment by Ekrekr** [comment]
Looks like the connection isn't set when something is called https://github.com/brianc/node-pg-cursor/blob/master/index.js

**Comment by BenBirt** [comment]
I've filed https://github.com/brianc/node-postgres/issues/2389.
