### ISSUE TITLE
It shouldn't be possible to stop/resume a run in the middle of holding a client lock

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#1014]
This line means that runs can be 'stopped' (for later resumption) while the Runner is holding a lock on the warehouse client: https://source.cloud.google.com/tada-analytics/github_dataform-co_dataform/+/master:api/commands/run.ts;l=382?q=run.ts

This actually breaks how we run Redshift/Postgres transactions (but presumably occurs extremely rarely).

**Comment by Ekrekr** [comment]
Redshift and Postgres transactions no longer apply
