### ISSUE TITLE
Support multiple unique key assertions

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#1029]
Currently only one combination of keys in a table can be used for a uniqueness assertion.

Extending the API here will require a breaking change, or a new option, perhaps `uniqueKeys` rather than `uniqueKey`.

```
config {
  assertions: {
    uniqueKeys: [
      ["a", "b"],
      ["d", "e"]
     ]
  }
}
```

That would allow specifying multiple combinations of fields that should each be unique.

**Comment by rumbin** [comment]
see also: https://dataform.canny.io/feature-requests/p/add-uniqueness-assertions

**Comment by BenBirt** [comment]
We actually used to have this API, but it was removed before we implemented the feature. Adding it back sounds good...
