### ISSUE TITLE
"api" package should not depend on "core"

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#107]
core is *only* responsible for running the JS in user's project files.

api is responsible for everything except that, i.e. connecting to the user's data warehouse, running the compiled graph, etc.

Projects themselves should only need to depend on core. Developers using dataform should only need to depend on the api (but not core).

Let's make a strict line where the api and core packages only communicate via the shared protobufs, and api has strictly no dependencies on core. Any shared code can be pulled out to a utils package.

**Comment by canetcesc** [comment]
I'd suggest setting this issue as depending upon the completion of issue #247: if we can remove all the validation that occurs in `core/utils.ts` then there will be less of a dependency on core from api.

**Comment by Ekrekr** [comment]
Closing as @dataform/api is no longer being published
