### ISSUE TITLE
Line numbers in error messages for compiled SQL are off

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#108]
This is due to how the SQL get's compiled.

A quick fix for this would be to:

- [ ] Change the compiler code to not start any new lines before the actual query contents (this will break line 1's column numbers but that's less important and they are broken anyway)
- [ ] Make sure when we extract JS blocks, we keep empty lines in their place

---
Moved from dataform-co/dataform-tracking#124
/cc @lewish

**Comment by BenBirt** [comment]
@emilywilson2 for updates

**Comment by BenBirt** [comment]
Some cleanup update:
1. https://github.com/dataform-co/dataform-co/issues/876 will help with this a long way
2. Next, let's highlight the relevant line(s) in compiled queries on the RHS sidebar
3. Longer-term, let's track back the line number to any JS where we can (at a lower priority though, this is hard, probably involves adding sourcemaps)

**Comment by dwl285** [comment]
When we do this, we should a) highlight the line number the error is on, and b) default show the compiled query (5 lines before error + error line + 5 lines after error) if there is a compilation error
