### ISSUE TITLE
Allow but ignore trailing semi colons in pre/post_operations

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#1085]
Currently Dataform throws an exception when using a semi colon at the end of a pre_operation, for example in BigQuery:

```
config {
  type: "table",
  hermetic: true
}

pre_operations {
  declare x string;
}


select 1 as test
```

Throws the error `Semi-colons are not allowed at the end of SQL statements.`. This is a common use case for pre/post operations, and while dataform will add a semi colon, omitting it is unnatural.

Proposal: Allow trailing semi-colons on pre/post operations, only adding them in if they don't already exist (ignoring any trailing whitespace).

**Comment by BenBirt** [comment]
dup of https://github.com/dataform-co/dataform-co/issues/8591, fixed in `1.15.5`
