### ISSUE TITLE
Be able to pass parameters to dataform run command

### ISSUE THREAD

**Issue by Altons** [dataform-co/dataform#1175]
As I data engineer I would like to be able to pass parameters to a pipeline in bigquery as

`dataform run --tags countryReport --vars {country:"UK", department:"marketing"}`

which will inject the parameters in my `sqlx` as

```sql
select * from 
 ${ref("report_mart")}
 where country = ${vars.country} and department =  ${vars.department}
```

and compiled version would look like this:

```sql
select * from 
 `my_project.my_dataset.report_mart`
 where country = "UK" and department =  "marketing"
```

This will enable the creation/update of  tables reusing the same logic.

**Comment by BenBirt** [comment]
I don't love the JSON blob model because bash makes it a bit of a pain to use. I'd suggest `--var foo=bar --var baz=qux --vars=foos=bars,bazs=quxs`
