### ISSUE TITLE
Dataform validation error when using $$ quotes

### ISSUE THREAD

**Issue by markledwich2** [dataform-co/dataform#1191]
Snowflake allows `$$` as an alternate to quotes when you don't want backslash to escape. It's helpful for keeping regex readable. 

But the following query `select 'vdjpmf-sdfd' regexp $$v\w{5}-.*$$` makes Dtaform query validation fail when it runs successfully.

**Comment by Ekrekr** [comment]
This stems from the lexer, and would be fixed by sqlx v2
