### ISSUE TITLE
Some UI popups/containers are needlessly small

### ISSUE THREAD

**Issue by markledwich2** [dataform-co/dataform#1192]
In general, the Dataform UI is fantastic. But.. The **new commit** and **view graph** dialogs are so annoyingly small I'm raising an issue. I have ample screen real estate yet you're making me scrolling around in tiny boxes like an animal.

This is what they look like for my project:
**Graph View:**
![image](https://user-images.githubusercontent.com/17095341/108436881-fe7a7b00-7297-11eb-98f3-da638e72dc5a.png)

**New Commit:**
![image](https://user-images.githubusercontent.com/17095341/108436971-1d790d00-7298-11eb-8445-4466089927de.png)

They should expand to fill the available space.

**Comment by Ekrekr** [comment]
Closing as legacy app is deprecated.
