### ISSUE TITLE
Less verbose unit testing

### ISSUE THREAD

**Issue by twlcek** [dataform-co/dataform#1202]
Hello,

unit testing tends to become a bit verbose for larger tables. 
It would be really nice if one could specify  `input` and `expect` in a mark-down like table syntax. 

```
input "table1" {
   columnName1 | columnName2        | columnName3
   "value 1"   | DATE("2021-02-02") | 4711
   "value 2"   | DATE("2021-02-03") | 4712
}
```
Dataform could then auto-generate the SQL statements needed.

The spockframework (https://spockframework.org/spock/docs/1.0/data_driven_testing.html), which offers testing support in JVM environments, has a similar concept of Data-Tables.

**Comment by Ekrekr** [comment]
I'm closing this, as implementing a new syntax is a lot of overhead, and there's not much interest in this request.

I would recommend using Javascript templating to reduce verbosity where possible!
