### ISSUE TITLE
support for dataform.projectConfig.vars.someValue when doing a Run Create using the REST API

### ISSUE THREAD

**Issue by swfz** [dataform-co/dataform#1216]
I want an option to override `dataform.projectConfig.vars.someValue` when doing a Run Create using the REST API

https://docs.dataform.co/dataform-web/api/reference#/definitions/RunCreateRequestRunConfig

From the above, it seems that only `tags` is specified.

Do you have any plans for support?

**Comment by BenBirt** [comment]
We do not currently have plans to add significant features to the existing Dataform app.

However, to implement this requirement, assuming the value for `vars.someValue` is reasonably static, I would suggest adding a new environment to `environments.json` with the relevant `var` overridden; then create a run via the API with that environment name specified.
