### ISSUE TITLE
Configure Dataform directory in Visual Studio Code Extension 

### ISSUE THREAD

**Issue by jansphil** [dataform-co/dataform#1226]
Hi all,

Thanks for providing the Visual Studio Code Extension. However when the Dataform directory is in a subfolder inside the project, the extension does not work, since it expects the `dataform.json` file to be in the root.

There could be a configuration property to be able to define the Dataform subdirectory.

Thanks!

**Comment by mokshasoul** [comment]
bumping this issue

**Comment by GJMcGowan** [comment]
This issue is now resolved, please update to version 0.0.13 and apply the new config https://github.com/dataform-co/dataform/pull/1639

**Comment by psvaiter** [comment]
Since it's resolved, what is the configuration property to define the Dataform subdirectory? I couldn't find it in the PR.

**Comment by p13rr0m** [comment]
There is the compiler options in VS Code that sets the project-dir argument:

![image](https://github.com/user-attachments/assets/ff2abd51-4082-4846-940a-9ca3a1d4121f)

![image](https://github.com/user-attachments/assets/8d34852c-a235-4a68-af04-bfbfcfc90e63)
