### ISSUE TITLE
`inline` models do not seem to respect referenced dependencies.

### ISSUE THREAD

**Issue by igofunke** [dataform-co/dataform#1228]
**Problem**

`inline` models do not seem to respect referenced dependencies.

**How to reproduce it**

1.  Create a file `a.sqlx` inside `definitions` and place the following code.

```
config {type: "inline"}
select "a" as A
```

2. Create a file `c.sqlx` inside `definitions` with the following code.

```
config {type: "inline"}
select "c" AS C
```

3. Create a file `b.sqlx` inside `definitions` with the following definition.

```
config {type: "view"}
select * from ${ ref("c") }
```

4. Run `dataform run --actions b`. Note the following error.
```
 > select * from ()
  bigquery error: Syntax error: Unexpected ")" at [3:16]
```

5. Change `b.sqlx` to read from `a.sqlx`
 ```
select * from ${ ref("a") }
```

6. Run `dataform run --actions b`. Note the view is created successfully.

```
Dataset created:  warehouse.b [view]
```

**Expected behaviour**

Step 4. should resolve the dependency and bring in the contents of `c.sqlx`

**Comment by BenBirt** [comment]
Thanks for the report!

This is a known issue. `inline` models should not be used any longer (at least in part for this reason), they're not documented (though if you have found somewhere, please tell me and I'll remove it!), and the support only remains in the framework for backwards compatibility with (very) old users.

**Comment by igofunke** [comment]
Thanks for the fast answer! I found it digging in the code. I think they are really useful so it's a pity that they have been deprecated. What is the workaround if I want to get an intermediate model that I don't want to materialise in my warehouse? Splitting in intermediate models not only helps reducing complexity but also helps to test multiple parts better.
