### ISSUE TITLE
[question] JS function to return result of the SQL query?

### ISSUE THREAD

**Issue by mmartsen** [dataform-co/dataform#1241]
Is it possible to do that? smth similar to:

```
js {
  function getPartitions() {
     return operate()
                  .query("select ARRAY_AGG(partition_id) from bigquery.some_table")
                  .collect()
  }
}
```

`select * from bigquery.partitioned_table where int_partition_column in unnest(${getPartitions()})`

this way it would be possible to overcome limitations in bigquery partition pruning for range partitioned tables.

If that's not possible to do with internal dataform api, is is theoretically possible to do by adding google-bigquery dependency to package.json and writing similar function from scratch?

**Comment by lewish** [comment]
This is a hard limitation of Dataform - even if you pulled in the google-bigquery API, you would not be able to call it. There's more information about why that is the case here - https://docs.dataform.co/guides/sqlx#sandboxing-for-fast-secure-reproducible-sqlx-compilation

However - there are some specific workarounds to this situation that should allow you to get pruning to work correctly - https://docs.dataform.co/warehouses/bigquery#optimizing-partitioned-incremental-tables-for-bigquery

**Comment by mmartsen** [comment]
Thanks for your answer @lewish 
We had implemented approach with pre_operation before and it work great. The idea was to make it more dynamic (ie to skip refresh) and avoid creating additional tables by using the view instead, but still with partition pruning
