### ISSUE TITLE
Dataform encountered an error: Compilation timed out

### ISSUE THREAD

**Issue by talktokunalkishor** [dataform-co/dataform#1245]
We are running Dataform on a  Citrix Windows Server. Dataform version is 1.19.0.

However, whenever we try to compile or run the SQLX file, it gives error as,

Dataform encountered an error: Compilation timed out
Error: Compilation timed out
    at Timeout.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\@dataform\cli\bundle.js:25678:91)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

We even changed the Dataform installation location still the same error. We tried compiling/running the same command multiple times still the same...
Compiling...

Dataform encountered an error: Compilation timed out
Error: Compilation timed out
    at Timeout.<anonymous> (R:\dataforminstall\node_modules\@dataform\cli\bundle.js:25678:91)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Please suggest the way out.

**Comment by BenBirt** [comment]
It's possible that this is some form of Windows incompatibility.

Can you tell us if this happens on a specific project, or if it happens for an empty one - i.e. is there some special about your files?

I'd also suggest using the Dataform Docker image to help debug this / give us more information about what's going on.

**Comment by talktokunalkishor** [comment]
Thats the irony.. for another user who is using the same environment.. its working just fine.. I'll test and let you know.. meanwhile is there anyway to generate detailed log to figure out the problem ?

**Comment by talktokunalkishor** [comment]
Hi @BenBirt , Ran it with a Blank project and still the same issue. Would like to know, how to generate/find detailed logs of execution .

**Comment by BenBirt** [comment]
Can you clarify: in both environments, is the timeout intermittent? Is the timeout intermittent even on an empty project? Do you see the same behaviour using our [Docker image](https://hub.docker.com/r/dataformco/dataform)? 

If the behaviour truly is intermittent in all environments, I'd wonder about how busy these machines are. Compilation essentially creates a child process which does the actual job of compiling your code; that child process is given (in the CLI) 5 seconds to complete.

There aren't currently any options for generating more detailed logs, but I would suggest watching processes on your machine when you trigger a compile (I'm not sure how to do this on Windows, on a Mac I'd use `htop`). If you filter for processes containing `node`, you should see two processes spin up when you run `dataform compile` - the parent, which is just the CLI, and the child, which is doing the compilation. If you see both spin up, and the child runs for 5s and you see the timeout, then we'll know something is wrong in that child process. (Right now I'd like to verify that something on the system isn't preventing that child process from running, or killing it early, or something.)

**Comment by talktokunalkishor** [comment]
Hi @BenBirt, Yes you are 100% correct and that’s the same observation I had. To solve this I edited the bundle.js file and increased the timeoutmillis variable as well as 5 ms to 10 mins and since then I haven’t encountered timeout !!!

**Comment by BenBirt** [comment]
I'm extremely surprised, to be honest! I'd expect only the most complex of Dataform projects to take over 5s to compile on a modern machine - would you mind sharing the specs?

It's obviously not great that you're having to edit our code to do this - I've created https://github.com/dataform-co/dataform/issues/1246 to track a CLI flag that would allow you to do this.

**Comment by talktokunalkishor** [comment]
Hi @BenBirt , Well in our observation, we have encountered this problem even on standalone machines, however the frequency is pretty less. The config of Citrix environment is high ( 16 CPUs with 512 GB RAM) but so are number of users sharing the same environment. Hence we observe slowness at times mostly when all users are using.  I agree that we shouldn't be editing the core code but this small change allowed us to solve our problem for the time being. If a flag could be added that would be wonderful ( Something like wait/nowait during run/compilation)

**Comment by BenBirt** [comment]
Thanks for all the input here. I'm going to close this in favour of https://github.com/dataform-co/dataform/issues/1246 (and work on that issue today).
