### ISSUE TITLE
Make compilation timeout configurable via CLI flag

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#1246]

**Comment by BenBirt** [comment]
`--timeout` flag added in version `1.20.0`. You can pass arbitrary duration strings, e.g. `--timeout=10s` or `--timeout=5m`.

**Comment by sukhamritboparai** [comment]
Thanks a-lot, this was precious.

**Comment by Murry-Ovo** [comment]
@BenBirt is there any way to customise the timeout flag via the web UI? We are still frequently (once or twice a week) getting the error message on our scheduled runs:
`Unable to compile project: Unable to compile project: Compilation timed out`

**Comment by BenBirt** [comment]
Unfortunately not - we (Dataform) need to retain control of compilation timeouts in the webapp.

If you're hitting compilation timeouts, the best things to do are:
- remove dead code
- consider splitting your project into smaller units
- consider wider use of the JavaScript API (using which avoids SQLX -> JavaScript transpilation)
