### ISSUE TITLE
Dataform compilation error in docker image with high no of definitions

### ISSUE THREAD

**Issue by sukhamritboparai** [dataform-co/dataform#1258]
We have setup a docker image to run dataform cli in it and while compiling  using **_dataform compile_**  we are facing following error:

**Dataform encountered an error: Compilation timed out
Error: Compilation timed out
    at Timeout.<anonymous> (/usr/local/lib/node_modules/@dataform/cli/bundle.js:25678:91)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)**

While the compile is successful outside docker container i.e in IDE terminal and also successful with lets say 150 definitions in docker container. When the definitions no. increases within docker container, the compilation error occurs. **_FYI, we are using official dataform docker image to run dataform compile command_**

**Comment by BenBirt** [comment]
I think you'll be able to work around this with a fix to https://github.com/dataform-co/dataform/issues/1246. I will work on it today.
