### ISSUE TITLE
CLI feature request: Support building an action + dependencies

### ISSUE THREAD

**Issue by elyobo** [dataform-co/dataform#1266]
Manually specifying tags and actions on the CLI gets you a long way, but I'd often like to be able to build a specific table _and also all of the things it depends on_. Figuring these out and specifying them manually is painful and error prone; dataform has the dependency tree and so could figure out the right things to build in the right order, e.g. `dataform run --target-action my_table_name` could run not just `my_table_name` but everything it depends on.

**Comment by BenBirt** [comment]
Unless I'm misunderstanding, we already support this, via the `--include_deps` flag.

(See `dataform help` or `dataform help run` for more details.)

**Comment by elyobo** [comment]
Not sure how I’ve repeatedly missed that! Thanks and apologies for the
noise.

**Comment by elyobo** [comment]
Not sure if I had tried that in the past and then forgotten at some time in the past, because it doesn't seem to work. Apologies if this is a support request but this seems like the obvious usage.

```
$ npx dataform --version
1.19.0
```

```
$ npx dataform run --actions my_table --include-deps --dry-run
Compiling...

Compiled successfully.

Dry run (--dry-run) mode is turned on; not running the following actions against your warehouse:

1 dataset(s):
  dataset.my_table [table]
```

```
$ npx dataform run --actions my_table --include-deps
Compiling...

Compiled successfully.

Running...

Dataset created:  dataset.my_table [table]
```

**Comment by BenBirt** [comment]
Hmm, I just tried to repro this and couldn't. Can you share some more about your project, or a minimal repro case?

In `definitions/test.sqlx`:
```
config { type: "view" } ${ref("view2")}
```

In `definitions/view2.sqlx`:
```
config { type: "view" } select
```

```
➜  test-dataform dataform compile
Compiling...

Compiled 2 action(s).
2 dataset(s):
  dataform.test [view]
  dataform.view2 [view]
➜  test-dataform dataform run --dry-run --actions test         
Compiling...

Compiled successfully.

Dry run (--dry-run) mode is turned on; not running the following actions against your warehouse:

1 dataset(s):
  dataform.test [table]
➜  test-dataform dataform run --dry-run --actions test --include-deps
Compiling...

Compiled successfully.

Dry run (--dry-run) mode is turned on; not running the following actions against your warehouse:

2 dataset(s):
  dataform.test [table]
  dataform.view2 [table]
```

**Comment by elyobo** [comment]
Thanks, I'll see if I can strip mine down to a minimal reproduction. There isn't anything unusual about it that I'm aware of, but there must be something!
