### ISSUE TITLE
Option to pre-load config args

### ISSUE THREAD

**Issue by Tristan-Crudge** [dataform-co/dataform#1267]
hi, 
first time contributer so if you need me to revise, please let me know. 

As a user of dataform, I would like to able to template the config block so _my_ arguments are already present when I create a new file within my project.

Problem:
I create a new file and I have the following template shown to me 
```
config {
  type: "view"
}
```
I need to add descriptions, tags, name, columns and schema every time. 
I have to add this in manually myself every time. 

Solution:

I would like the ability to configure a new_file template for my most common use case and upon file creation I would have my built template.
e.g - 
```
config {
        type: 
        ,name: 
        ,schema:
        ,description:
        ,tags: 
        ,columns:
}
```

**Comment by andres-lowrie** [comment]
this may not be what you're looking for, but I have solved this problem outside of dataform via script

I think doing this outside of dataform allows for the most flexibility in any case since my script is not "limited" to the context of dataform.

**Comment by Ekrekr** [comment]
I think Andres is spot on here, this is something that would best exist outside of Dataform Core, or the CLI.

If a lot of time is being spent on writing lots of similar SQLX files, then it would likely be better to use the JS API to populate them in a loop.
