### ISSUE TITLE
Docs question: Why `---` for pre- and post-operations?

### ISSUE THREAD

**Issue by elyobo** [dataform-co/dataform#1274]
https://docs.dataform.co/guides/datasets/publish says

> To specify multiple operations, separate them with --- :

Is there a reason that this is preferable to using semicolons to specify multiple statements?

**Comment by BenBirt** [comment]
Only some DB engines allow us to pass multiple statements in a single query (BigQuery being one such). If you're using one of those - feel free to just use semicolons.
