### ISSUE TITLE
Can't use json files on includes folder on v1.20.0 (snowflake)

### ISSUE THREAD

**Issue by guilhermealc** [dataform-co/dataform#1282]
When I try to use any javascript files on my dataform clean project, I get an error on version 1.20.0.
I tested on 1.17.0 and it works fine.
![image](https://user-images.githubusercontent.com/29486566/139842457-7e73da13-aee0-41cf-85cf-8888cfd8afb2.png)

**Comment by Ekrekr** [comment]
Can you provide replication instructions please?
