### ISSUE TITLE
Backslashes in regular expressions removed when running .ops.sql files.

### ISSUE THREAD

**Issue by jkukul** [dataform-co/dataform#1292]
Let's say I have a `test.ops.sql` file that looks like this:

```sql
SELECT regexp_extract('01a_data_engine', r'^(\d{2}\w)'),
              regexp_extract('01a_data_engine', '^(\\d{2}\\w)')
```

when running it (dataform run --actions `test.ops.sql`), what is actually executed in BQ:

```
SELECT regexp_extract('01a_data_engine', r'^(d{2}w)'),
              regexp_extract('01a_data_engine', '^(\d{2}\w)')
```

This looks very similar to https://github.com/dataform-co/dataform-web-tracking/issues/200 but applies to `.ops.sql` files.

**Comment by Ekrekr** [comment]
Closing as `.ops.sql` files are deprecated
