### ISSUE TITLE
Override database config is not applied to Auto generated assertions

### ISSUE THREAD

**Issue by newuniverse** [dataform-co/dataform#1295]
About this https://docs.dataform.co/guides/assertions#auto-generated-assertions .

I am using `dataform run --vars` option to embed a new database(GCP project_id) into each sqlx files to
override the default_database  in my CI/CD.

Not from code base but from behavior base, I found that override is not applied to auto generated assertions.

Is it an expected  behavior or just a bug?

For example: 

`dataform.json`
```
{
    "warehouse": "bigquery",
    "defaultSchema": "dataform",
    "assertionSchema": "dataform_assertions",
    "defaultDatabase": "my-dev-project"
}

```

`some_query.sqlx`
```
config {
  type: "table",
  database: dataform.projectConfig.vars.embed_my_prd_database,
  assertions: {
    uniqueKey: ["user_id"],
    nonNull: ["user_id", "customer_id"],
    rowConditions: [
      'signup_date is null or signup_date > "2019-01-01"',
      'email like "%@%.%"'
    ]
  }
}
select ...
```

If you run `dataform run --actions=some_query --vars=embed_my_prd_database=my-prd-project`

expect: success

but I got followings because I was using SA credential of `my-prd-project` not of `my-dev-project`
```
Assertion failed:  dataform_assertions.some_query_assertions_uniqueKey_0
  > 
  >       create or replace view `my-dev-project.dataform_assertions.some_query_assertions_uniqueKey_0` as
```

**Comment by Ekrekr** [comment]
A more elegant solution that we have planned for this is CLI flags for `dataform.json` parameters.

**Comment by newuniverse** [comment]
I'm looking forward to it!

**Comment by Ekrekr** [comment]
I think this boils down to the [config not being contextable](https://github.com/dataform-co/dataform/blob/08be45fd193ddc856e69c8590a330024051eb7bc/core/compilers.ts#L75).

The var is for `config` is correctly defined in the raw string there:

```
🚀 ~ file: compilers.ts:55 ~ compileSqlx ~ config: {
  type: "table",
  database: dataform.projectConfig.vars.var1,
}
```

But because `config` is not contextable [during publish(https://github.com/dataform-co/dataform/blob/08be45fd193ddc856e69c8590a330024051eb7bc/core/session.ts#L155), dataform ends up being undefined:

```
🚀 ~ file: table.ts:274 ~ Table ~ config ~ config: { name: 'file', type: 'table', database: undefined }
```

**Comment by Ekrekr** [comment]
I'm a bit stumped by this, but I've narrowed down the issue and it is clear it only happens in the CLI.

Adding more tests for Dataform Core (https://github.com/dataform-co/dataform/pull/1603) demonstrate that:
* Variables are being correctly loaded from the project config override.
* Variables can be correctly loaded as the database for tables.
* Variables can be correctly loaded as the database for auto assertions.

Adding more tests for Dataform CLI (https://github.com/dataform-co/dataform/pull/1603) demonstrate that:
* Variables are being correctly loaded from the project config override.
* Variables can be correctly loaded as the database for tables.
* However for auto assertions, the variable is not applied.

**Comment by btelFD** [comment]
Also running into this. We set the database in the config block of each .sqlx and assertions in the config block don't work
