### ISSUE TITLE
Reference the ref() method from a js file in the `includes/` folder 

### ISSUE THREAD

**Issue by francescomucio** [dataform-co/dataform#1296]
I am working on a dataform project using two different bigquery projects, so where I use ref()  I need always to specify the project, dataset, and table.

I was wondering if there is a way to wrap the ref() method in two methods like project1_ref and project2_ref and avoid passing the bigquery project all the time (edited)

I tried to create a wrapper method in includes/utils.js but it didn't work out. Any idea?

What I would like is something like:

```js
module.exports = {
  ref: {
    npii: (...args) => ref(dataform.projectConfig.vars.nonPiisDatabase, ...args),
    pii: (...args) => ref(dataform.projectConfig.defaultDatabase, ...args)
  }
}
```
that I can use like `${utils.ref.pii('schema', 'table')}`

What I am trying to achieve is a ref() method where I don't need to include all the time the database argument. 

Why I need the database argument? because I want to be explicit on which BQ project I am using.
Why I don't want to include it? because I want to keep my code lean.

**Comment by BenBirt** [comment]
When you say this didn't work out, can you clarify? What happened? (You should definitely be able to write *something* like this!)

**Comment by francescomucio** [comment]
sorry, I missed that part. In the sqlx files using `utils.ref.pii` I get a `ReferenceError: ref is not defined` error.

This goes away if I write something like:

```js
  ref: {
    npii: (...args) => [dataform.projectConfig.vars.nonPiisDatabase, ...args].join('.'),
    pii: (...args) => [dataform.projectConfig.defaultDatabase, ...args].join('.')
  }  
```

Which works, but breaks all the dependencies. The problem is that the includes/utils.js doesn't know about the `ref()` method

**Comment by BenBirt** [comment]
Ah, understood - this is because `ref` is actually a method of `IContextable` (i.e. should be called as `ctx.ref(...)`). SQLX files are "magic" in that they know the current context, so provide a `ref` function directly.

I believe something like the following should work:

```
module.exports = {
  ref: {
    npii: (ctx, ...args) => ctx.ref(dataform.projectConfig.vars.nonPiisDatabase, ...args),
    pii: (ctx, ...args) => ctx.ref(dataform.projectConfig.defaultDatabase, ...args)
  }
}
```

And you can call these from SQLX or other JS like: `utils.ref.pii(ctx, ...)`.

**Comment by francescomucio** [comment]
Thanks, at the end we went to create a second js file `includes/database` which we use as `ref(database.pii, "schema", "table")`, which satisfy our desire of clarity and brevity :)
