### ISSUE TITLE
Search not working in Run logs web page

### ISSUE THREAD

**Issue by VijayaKumar-sivakumar** [dataform-co/dataform#1317]
Hi,

No search results returned, on searching by trigger name. 
Please find the screenshot.

![run logs page](https://user-images.githubusercontent.com/86209444/155488337-25d46ee9-41b8-4761-b315-1f30179c938e.png)
![search by manual](https://user-images.githubusercontent.com/86209444/155488342-754d59e3-f2f8-4f5e-abc8-bc6b38024546.png)

**Comment by Ekrekr** [comment]
Closing as app.dataform.co is deprecated in favor of the GCP version
