### ISSUE TITLE
Scheduled job shows wild deviations in BigQuery's CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by VictoryJin** [dataform-co/dataform#1323]
We recently implemented an incremental BigQuery batch job that runs every 20 minutes, and log a parameter with `CURRENT_TIMESTAMP` from pre-operations when the job was executed. 

I'm seeing large deviations when BigQuery records this parameter from the expected 20 minutes (deviations plotted below, x-axis in seconds). Is there any best practice if I want this to be consistent as of when the job was run? Thanks!
![image](https://user-images.githubusercontent.com/23367869/156416906-b16190bc-12cf-45ca-96d3-4376e5401283.png)

**Comment by Ekrekr** [comment]
Closing as app.dataform.co is deprecated in favor of the GCP version.

Just FYI, these deviations happen because we spread out runs from happening on the dot, to prevent overloading the system - as you'd expect runs are more likely to be scheduled for on the hour.
