### ISSUE TITLE
allow setting tracking behavior via flag in cli

### ISSUE THREAD

**Issue by andres-lowrie** [dataform-co/dataform#1333]
Hello 👋 

It would be really cool to have a flag that can be passed to the cli which would set the value of the tracking settings instead of having to modify the `settings.json` file directly, it's easier than having to manage another file. 

The use case we have is one of CI/CD where we're running dataform via the cli and currently we have to create a settings file to avoid getting prompted on runs.

The flag can go both ways, doesn't really matter the goal is just to have a non-interactive command 

```shell
dataform run --track ...

# or 

dataform run --no-track ...

```

anything really 

Thanks y'all

**Comment by GJMcGowan** [comment]
This is fixed in https://github.com/dataform-co/dataform/pull/1450

Released in `2.4.1`
