### ISSUE TITLE
Allow Big Query Materialized Views to be partitioned and have column descriptions.

### ISSUE THREAD

**Issue by ianatkinson-ee** [dataform-co/dataform#1334]
We would like to be able to use Dataform to create Big Query Materialized Views with partitions and column descriptions.

Materialized Views in Big Query can have partitions (https://cloud.google.com/bigquery/docs/materialized-views-create#partitioned_materialized_views) and column descriptions. In Dataform when we try and do this we get errors. E.g. for partitioning we get a File has compile error:
![Screenshot from 2022-04-21 10-20-51](https://user-images.githubusercontent.com/94376074/164423464-7308f2a7-a544-44fa-8f72-1abc317c9b79.png).

**Comment by damienhollis** [comment]
This seems like a pretty straightforward bug, is there a reason it hasn't been addressed?

**Comment by Ekrekr** [comment]
Closing, as this has been implemented in https://github.com/dataform-co/dataform/pull/1660 (thanks so much @vlad-ogol!) and plumbed through in GCP b/323396829.
