### ISSUE TITLE
Support for Teradata 

### ISSUE THREAD

**Issue by SatishChGit** [dataform-co/dataform#1336]
Planning to add support of Teradata in dataform.

**Comment by SatishChGit** [comment]
Hi Folks,


We are planning to create new dataform plugin for teradata. Please assist on this.

Regards,
Satish Ch

**Comment by G2H** [comment]
Hi Satish - it's unlikely we'll be able to add support for Teradata anytime soon. 

You are more than welcome to submit a pull request for this if that could of interested. This [blog post](https://dataform.co/blog/how-to-add-a-new-warehouse-adapter-to-dataform) has a few pointers to get started.
