### ISSUE TITLE
Adding new Schedule refreshes while typing name

### ISSUE THREAD

**Issue by Goldeneyes15** [dataform-co/dataform#1340]
When adding a new schedule in the environments.json GUI, while typing in the Schedule name field, the file tab will refresh erratically. 

Steps to reproduce:
1. Open environments.json
2. Create new Schedule
3. Type in the "Schedule name" field
4. The file tab should refresh before you are finished typing
5. If the string is the same as an existing schedule, the GUI will refuse to load, forcing the user to switch to plaintext to delete/fix their new schedule

**Comment by BenBirt** [comment]
The dataform app is currently in maintenance-only mode, so unfortunately we won't be able to fix this.
