### ISSUE TITLE
Schedule tags are unsorted

### ISSUE THREAD

**Issue by Goldeneyes15** [dataform-co/dataform#1341]
When selecting tags to run in a new schedule, the list is not sorted. Very inconvenient for users with many tags. In addition, when scrolling through the tags the list will randomly scroll back up to the top. Tested in a project with 300+ tags

Steps to reproduce:
1. Navigate to environments.json
2. Create a new Schedule
3. Under "Tags to run", the dropdown is unsorted
4. When scrolling, occasionally the list will randomly scroll to the top

**Comment by BenBirt** [comment]
The dataform app is currently in maintenance-only mode, so unfortunately we won't be able to fix this.
