### ISSUE TITLE
Error: Error: 2 UNKNOWN: Failed to merge from remote branch

### ISSUE THREAD

**Issue by gabrieldomene** [dataform-co/dataform#1369]
Hello guys 👋

I'm facing the error described in the title, a while ago I had to change the reference from master/main due to the way dataform create the names and the way it is now in github and after that no change is keeping up with the main noir can I do a pull in other branches. But the most odd thing is if a create a new branch and start the work from there, dataform will never update the main even though the github is updated and "right" with the commits sent.

Error code: Error: Error: 2 UNKNOWN: Failed to merge from remote branch
Response from support: I am not receiving any feedback on this issue internally, so I wanted to suggest that you reach out on the Dataform Slack channel
Slack channel: None so far (will edit if received)

**Comment by Ekrekr** [comment]
Closing as app.dataform.co is deprecated in favor of the GCP version.

FYI You'll need to change the default tracking branch used in the Dataform app settings - we don't read the default tracking branch from GitHub!
