### ISSUE TITLE
Make `defaultLocation` accessible to user code

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#1371]
(via `dataform.projectConfig`)

See https://buganizer.corp.google.com/issues/244881326

**Comment by mokshasoul** [comment]
This would also help this issue: https://github.com/dataform-co/dataform/issues/1226


I started using the extension but I am unable to work with it as it is not configurable

**Comment by Ekrekr** [comment]
Fixed in https://github.com/dataform-co/dataform/pull/1705
