### ISSUE TITLE
Error : Dataform compile fails - Assigning to rvalue

### ISSUE THREAD

**Issue by latika-wadhwa** [dataform-co/dataform#1379]
One of our customer is trying to execute the Dataform code (https://github.com/latika-wadhwa/dataform_reusable_scd2) on a Windows Local machine but it ends up failing with SyntaxError - Assigning to rvalue (as below). 
Also note that, the above code works fine on a Mac local and Google Cloud Shell but somehow gives an error on Windows Local (clients preferred).  

![image](https://user-images.githubusercontent.com/48508718/194938587-d8eac5d3-5668-47d7-bba2-621feac3ecd9.png)

**Comment by kkulczak** [comment]
Have the same problem.
Using `dataform/cli` in version `1.22.2`

**Comment by scott-hobbs-uk** [comment]
Hi, I had this same issue on a native windows installation of node.js, so it seems to be windows specific. I couldn't find a direct workaround on a windows install, but for anyone finding this later an installation of node.js on WSL doesn't appear to have the same issue https://learn.microsoft.com/en-us/windows/wsl/install

A short summary of the installation process(these are expanded on by the WSL docs)
install the linux extension for windows
install node.js via curl on the linux extension
install required packages (globally) on the linux extension
install the gcloud cli on both (review the google auth documentation if you need help here, but essentially it's using the google auth application-default --no-browser options)
authorise on the linux by passing a website string which you visit on windows, then pass a code back
extend the timeout on compilation on the linux for windows environment
compile/run as if it were linux.

I hope this helps anyone else who comes across this issue!

**Comment by BenBirt** [comment]
Thanks for posting this workaround.

In addition, this bug should be fixed as of `2.0.4`: https://github.com/dataform-co/dataform/releases/tag/2.0.4
