### ISSUE TITLE
dynamically change schema for input block

### ISSUE THREAD

**Issue by marlena-hammond** [dataform-co/dataform#1381]
I am trying to use a js function to dynamically change the schema in a unit test if the environment is staging or prod. I can get the function to work in a sqlx file where it is creating a view or table, but I can't get it to work with the `input` block. Is this feasible? or does the input block only accept a string value?

Function that returns the staging schema depending on the environment:
```
function envSchema(input) {
  if (dataform.projectConfig.vars.executionEnvironment === "prod") {
    return input
  }
  else {
    return input + "_staging"
  }
}

module.exports = {
  target_dataset
};
```

hardcoded (would work for staging environment but not prod):
`input "schema_name_staging", "table_name" {`

attempt_1:
`input envFunc.envSchema("schema_name"), "table_name" {`
error: `Error thrown: Table "s" must be qualified with a dataset (e.g. dataset.table)..`

attempt_2:
`input "${envFunc.envSchema('schema_name')}", "table_name" {`
error: `Error thrown: Syntax error: Expected end of input but got keyword INPUT at [33:1].`

attempt_3:
`input ${envFunc.envSchema("schema_name")}, "table_name" {`
error: `Error thrown: Table "s" must be qualified with a dataset (e.g. dataset.table)..`

attempt_4:
```input `ref(envFunc.envSchema("schema_name"), "table_name")` {```
error: `Error thrown: Syntax error: Expected end of input but got keyword INPUT at [33:1].`

**Comment by marlena-hammond** [comment]
@BenBirt looks like you are the one to update the input block logic. Do you have any thoughts on this?

**Comment by BenBirt** [comment]
I'm not sure I understand this.

Unit tests don't run as part of DAG execution - they are intended to be manually executed (or automatically triggered as part of e.g. PR creation).

As such they are effectively environment-less, i.e. the schema/table that you're referencing here should be the "default" one for each input.

Does that make sense?
