### ISSUE TITLE
Consider allowing configurable incremental table truncation

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#1383]
originally https://buganizer.corp.google.com/issues/254402114

**Comment by Ekrekr** [comment]
Adding a new config for tables is a fair amount of overhead, and the syntax for truncating tables is simple enough to make this feature seem not worth it. https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#truncate_table_statement.

```
pre_operations {
  TRUNCATE TABLE staging.last_few_days
}
```

Feel free to re-open this with more points, or if I've misunderstood the request!
