### ISSUE TITLE
Dataform Docker CLI image not installing

### ISSUE THREAD

**Issue by NewUser2166** [dataform-co/dataform#1389]
Hi,
I am trying to run **install dataform** command using Azure devops with the YAML file mentioned below. 
`- script: |
    docker pull dataformco/dataform:latest
  displayName: 'Docker Pull'
- checkout: self
  displayName: Checkout code workspace dependencies
- script: |
    docker run dataformco/dataform:latest install
  displayName: 'Dataform install dependencies'`
 
  
  Here is the error I am facing.
`/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/56e1b832-1bba-4f59-8fb3-46b938ee6612.sh
Dataform encountered an error: / does not appear to be a dataform directory (missing dataform.json file).
Error: / does not appear to be a dataform directory (missing dataform.json file).
    at check (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27353:19)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:27103:33
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:27103:16
    at Object.customChecks (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:1572:26)
    at Object.runValidation [as _runValidation] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2826:22)
    at Object.runCommand (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:434:19)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2651:25)
    at runCli (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27978:7)`

**Comment by BenBirt** [comment]
I don't know enough about Azure devops to be able to debug this completely, but it sounds like the `docker run` is not happening in the context of the Dataform project. Have you tried doing this locally? (i.e. docker pull/run on your local repo clone)

**Comment by NewUser2166** [comment]
Thanks Ben for your response. This is my pipeline yaml file in Azure. Just like GithubActions, I am running docker in the checkedout repository but it fails for some reason. Docker pull step is working. 


`trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
 
- script: |
    docker pull dataformco/dataform:latest
  displayName: 'Docker Pull'
- checkout: self
  displayName: Checkout code workspace dependencies

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'docker run dataformco/dataform:latest install'    
  displayName: 'Dataform install dependencies' 
`

**Comment by BenBirt** [comment]
Can you verify that this works locally?

**Comment by NewUser2166** [comment]
After pulling the docker image, I tried to install the docker image locally
F:\TempDocker>docker run docker.io/dataformco/dataform:latest install

But again getting the same error in my local machine. 
Dataform encountered an error: / does not appear to be a dataform directory (missing dataform.json file).
Error: / does not appear to be a dataform directory (missing dataform.json file).
    at check (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27353:19)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:27103:33
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:27103:16
    at Object.customChecks (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:1572:26)
    at Object.runValidation [as _runValidation] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2826:22)
    at Object.runCommand (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:434:19)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2651:25)
    at runCli (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27978:7)

**Comment by BenBirt** [comment]
Ah, sorry. You need to mount the project directory into docker.

For example, assuming you are currently in the project directory:

```
docker run -v $PWD:/project docker.io/dataformco/dataform:latest install /project
```

**Comment by NewUser2166** [comment]
Thanks ben
I have tried doing the same but I am not sure where is it going wrong
Here is the screenshot of the command

![Screenshot 2022-11-01 150758](https://user-images.githubusercontent.com/116947273/199252967-7965f349-a449-4ed9-8cf2-c28c3a4b0565.png)

And here is my project structure
![Screenshot 2022-11-01 150910](https://user-images.githubusercontent.com/116947273/199253221-9b838ec0-72af-4fef-a1b7-92a547230cf2.png)


Thanks

**Comment by BenBirt** [comment]
Looks to me like docker is complaining about the format of your 'volume' flag. I'm no Windows expert, but I would try something like:

`docker run --volume ${PWD}:/project ...`

**Comment by NewUser2166** [comment]
Thanks Ben
just another question
Can we refer the nested files in the include folder from sqlx and compile in cli? I am referring to the function "render" in Includes/NestedIncludeFolder/functionFile.js  from the example.sqlx but it fails to compile in cli
However same solution compiles in GCP.


![image](https://user-images.githubusercontent.com/116947273/199727615-31db2b1a-8fed-4bc6-80ed-71d15d3f99a8.png)
![image](https://user-images.githubusercontent.com/116947273/199727710-8d11437f-9657-405e-93aa-ec8e4dffcc35.png)
![image](https://user-images.githubusercontent.com/116947273/199727907-231dd6e4-d440-45d6-8eed-bbe9028ec651.png)

**Comment by giksy101** [comment]
Docker ultimately comes pre-installed with the Node.js and npm i -g @dataform/cli. We can simulate the docker ourselves. We can avoid the dependency this way. Hope this is helpful. Following is the github actions workflow job example. You can emulate the same in Azure Dev Ops pipeline aswell.

`jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile Dataform
    steps:
      - name: Repo
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
      - name: Dataform
        run: npm i -g @dataform/cli
      - name: Install Dependencies
        run: dataform install
      - name: Compile
        run: dataform compile`

**Comment by NewUser2166** [comment]
Thanks Ben
Just another thing
If I use the nested folders inside **Includes** folder to place my functions, they can only be accessed through this statement?
const {functioninFile} = require("filepath.js");


The query is compiling in the Dataform after adding the require function at the top
But it is failing to work in the BigqueryIf I copy the compiled query from Dataform preview of GCP, 
it has const {}= require(funciton path)  at the top and if I copy the compiled query to the bigquery, it fails to cmopile in Big Query.
Its also because Bigquery will just have the path to the function file, and there isn't any such function file in BigQuery. Here is the compiled result from the Dataform, which wont work in BigQuery


const {functionFile} = require("includes/NestedIncludeFolder/functionFile.js");
with tempFunction AS  ( functionFile.render("Function Argument") )
SELECT 1 AS testChange


PS: It compiles correctly in git pipeline, but fails if I copy the compiled result from GCP and run in BigQuery

**Comment by BenBirt** [comment]
I am not really sure what you mean. Just to verify that everything works, I just (successfully) created the following in GCP Dataform:

definitions/view.sqlx:
```
config {
  type: "view"
}

js {
  const subdirfile = require("includes/subdir/subdirfile.js");
}

${file.fileFunction()}

${subdirfile.subDirFileFunction()}
```

includes/file.js:
```
function fileFunction() {
    return "hello from file"
}

module.exports = {
    fileFunction
}
```

includes/subdir/subdirfile.js:
```
function subDirFileFunction() {
    return "hello from subdirfile"
}

module.exports = {
    subDirFileFunction
}
```

`view.sqlx`'s compiled output (correctly) looks like:
```
hello from file

hello from subdirfile
```

**Comment by NewUser2166** [comment]
Thanks Ben,
I was adding the const function without wrapping it in the js tag.
It works, thanks again.
