### ISSUE TITLE
Is there a way to check if a table exists before running the query? [BQ]

### ISSUE THREAD

**Issue by kalanyuz** [dataform-co/dataform#1390]
Would like to do a conditional rendering like ${exists(table_name)? query: ""} but can't seem to find any documentation or how tos.

**Comment by BenBirt** [comment]
Interesting, can you describe the use-case?

The closest we have today is `when(...)` in `incremental` tables: https://docs.dataform.co/guides/datasets/incremental

**Comment by astorrs** [comment]
This is how we've dealt with it in Dataform/BigQuery:

```
if exists (
  select
    1
  from
    ${ctx.self().split('.')[1]}.INFORMATION_SCHEMA.TABLES
  where
    table_name = 'table1'
) then <do some stuff>;
else <do some other stuff>;
end if;
```
