### ISSUE TITLE
Provide support for creating temp tables ( `CREATE TEMP TABLE` ) in big query  using Dataform

### ISSUE THREAD

**Issue by Rstar1998** [dataform-co/dataform#1391]
Provide support for creating temp tables ( `CREATE TEMP TABLE` ) in big query  using Dataform. Dataform as of now don't have any provision in config to create temporary tables.

**Comment by BenBirt** [comment]
Can you describe the use case?

Temporary tables only persist within the context of a single script, so I'm not sure how this would be useful.

**Comment by Rstar1998** [comment]
@BenBirt  In My usecase I create a temp table and using that temp table I insert and update records in other table.

**Comment by BenBirt** [comment]
@Rstar1998 could this potentially be expressed as an `incremental` table?

**Comment by Ekrekr** [comment]
I've run into requests for temporary tables several times recently, and every one of them has been better solved by using incremental tables.

Please re-open this issue with more information, if you've got examples where this isn't the case!
