### ISSUE TITLE
CLI automation for credentials generation

### ISSUE THREAD

**Issue by dardT** [dataform-co/dataform#1399]
Hi, 

I would like to automate the credential file generation for BigQuery in a CI pipeline, and unfortunately the CLI forces the user to fill parameters in a TTY.

It would be great to add parameters to the CLI (on the command `dataform init-creds`) for the authentication type (ADC/JSON), as well as the location of the project and its ID. 

Another solution would be to replace the CLI prompt library by another, which does not prevent user from piping data to it. 

Maybe I am mistaken and it is still possible to automate the CLI for credentials initialization, if so could you explain how?

Kind regards,

Tristan

**Comment by BenBirt** [comment]
In general, we would suggest using ADC. At that point it is safe to check-in the `.df-credentions.json` file, since it contains no sensitive data. Would this be possible for your use-case?

**Comment by BenBirt** [comment]
Ah, OK. In this case I would probably use something like `jq` to output a `.df-credentials.json` file using your JSON service account key. (That's essentially all that `dataform init-creds` does.)

**Comment by dardT** [comment]
Thank you
