### ISSUE TITLE
How to mock "current_timestamp()" in unit tests?

### ISSUE THREAD

**Issue by kkulczak** [dataform-co/dataform#1402]
Hi Team, 

I'm writing unit-test for table for data ingestion. Pipeline uses current_timestamp() BigQuery function.
Running tests with snippet bellow, results in error because timestamps have a difference of some milliseconds.

How can I mock it's value?
Or write tests for this table in a different way?

```
# table_a.sqlx
config {...}
SELECT 
   current_timestamp() as load_time,
   t.value as value,
   ...
FROM ${ref("table_b"} as t
```

```
# test_table_a.sqlx
config {type: "test", dataset: "table_a"}

input "table_b" {
   SELECT 1 as value
}

SELECT current_timestamp() as load_time, 1 as value
```

**Comment by mshakhomirov** [comment]
Hi @kkulczak 
- I use timestamp_format to round it to minutes.
- includes with java sctipt timestamp might help too, not 100% sure about this one:
-in test use:
```js
${constants.timeNow}
```
in includes/constants.js:
```js
const timeNow = Math.round(Date.now() / 1000);
module.exports = {
  timeNow
}
```

**Comment by kkulczak** [comment]
But this means, than I would have to use rounded `load_time` values in `table_a`, right?

I'm worries that buisness requirements do not allow me to do so.
