### ISSUE TITLE
No --verbose flag although mentioned in dataform CLI docs

### ISSUE THREAD

**Issue by teraearlywine** [dataform-co/dataform#1412]
https://docs.dataform.co/dataform-cli

dataform compile [project-dir]

Compile the dataform project. Produces JSON output describing the non-executable graph.

Positionals:
  project-dir  The Dataform project directory.  [default: \".\"]

Options:
  --help           Show help  [boolean]
  --version        Show version number  [boolean]
  --watch          Whether to watch the changes in the project directory.  [boolean] [default: false]
  --schema-suffix  A suffix to be appended to output schema names.
  --verbose        If true, the full contents of command output will be output (containing fully compiled SQL, etc).  [boolean] [default: false]

**Comment by Ekrekr** [comment]
Closing as those docs are out of date - use https://cloud.google.com/dataform/docs/reference/dataform-cli-reference instead. --verbose is no longer listed on an option on the CLI when run
