### ISSUE TITLE
How can I get the run log information details

### ISSUE THREAD

**Issue by Prempi** [dataform-co/dataform#1428]
@BenBirt How can I get the run log information detail when the schedules fail, could I use the REST API or other solutions to retrieve the error detail of specific dataset/assertion.

![image](https://user-images.githubusercontent.com/30255392/212828504-b093bba9-d320-4af7-8969-4767973e77ec.png)

**Comment by BenBirt** [comment]
If you want to debug why an assertion has failed: https://docs.dataform.co/guides/assertions#inspecting-failed-assertion-rows

**Comment by Prempi** [comment]
@BenBirt No, that's not my intention. My purpose is to notify the error log detail from scheduled running to microsoft team, so I need to extract the error log detail first.

**Comment by BenBirt** [comment]
Legacy Dataform has no API for this, unfortunately. The UI is the only way of determining error detail.

I would encourage you to switch to GCP Dataform, which has full API support.
