### ISSUE TITLE
Feature Request - Add option to run dependents of the specific actions(Dataform CLI)

### ISSUE THREAD

**Issue by Prempi** [dataform-co/dataform#1429]
I would like to request the new feature for Dataform CLI, to add the option to also run dependents of specific actions.

**Comment by andres-lowrie** [comment]
Do you mean running the dependents only or in addition to the action you're targeting, because if it's the latter you can do already do this with `--include-deps` flag like this 

```
dataform run --include-deps --action my-table
```

**Comment by andres-lowrie** [comment]
> Do you mean running the dependents only or in addition to the action you're targeting, because if it's the latter you can do already do this with `--include-deps` flag like this
> 
> ```
> dataform run --include-deps --actions my-table
> ```

my bad, I just realized you said `dependents` and not `dependencies`

**Comment by marcoskogaita** [comment]
If I got it right
I really think this is useful since it could prevent a full run when you want to update only the dependants after a table change

**Comment by a2wd** [comment]
Fixed by #1448
