### ISSUE TITLE
Dataform CLI outputs an AWS SDK message

### ISSUE THREAD

**Issue by wintermi** [dataform-co/dataform#1458]
The following is output when executing the Dataform CLI:
```
(node:25544) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Ekrekr** [comment]
A workaround for now is to set the Node environment variable: `NODE_NO_WARNINGS=1`

**Comment by karszawa** [comment]
`AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1` also works, but only for the AWS message.

https://github.com/aws/aws-sdk-js/blob/39e7e8a2b96374ec8e9573c8aaf96267d85d5175/lib/maintenance_mode_message.js#L31
