### ISSUE TITLE
dataform cli not able to locate core compiler when running in CI

### ISSUE THREAD

**Issue by raghavnarayanan** [dataform-co/dataform#1465]
I have 2.4.2 of @dataform/cli and @dataform/core installed in my project. The error I see when running the dataform run command in circleCI is:

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/9013020/224079392-89a24823-f610-4b9a-958e-2e27f4329eb3.png">

It appears to be stemming from this place in worker_bundle.js file in the dataform/cli library:

![image](https://user-images.githubusercontent.com/9013020/224079867-502fbc0e-e05b-4920-9af0-7cd84e7efd6b.png)

Does the cli expect the core to be in a certain location? Does there need to be a index.js for my project?

**Comment by BenBirt** [comment]
Can you confirm that you are running `dataform install` prior to `dataform run`?

**Comment by raghavnarayanan** [comment]
Thank you, I did not have that previously. I added it now, but see the below error: 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/9013020/224388358-79c7179a-7011-4c30-b4c2-74b4c4ba4222.png">


I used to get this, but I thought I had gotten past it by adding a commandline arg --track=false.

**Comment by raghavnarayanan** [comment]
Hi @BenBirt please let me know if I am missing any other step as part of the CI process. Thanks.

**Comment by BenBirt** [comment]
Hmm, this seems like a bug on our end. As a workaround, can I suggest that you explicitly opt-out of tracking in `settings.json`?

**Comment by raghavnarayanan** [comment]
So I tried having a settings json in the path /home/circleci/.dataform/settings.json with 
{
track: false
}

and I also tried to commandline force it like so:

yes n | dataform run

But both of those approaches didnt help get past the prompt question.

**Comment by BenBirt** [comment]
Can you try (in that file):

```
{
  "allowAnonymousAnalytics": false
}
```

**Comment by BenBirt** [comment]
Yes, there does need to be a `.df-credentials.json` file, but it does not need to contain any sensitive data. If you (manually) run the `dataform init-creds` command, and answer the resulting questions - taking care to answer that you want to use ADC to authenticate to BigQuery - then the resulting file will not contain any sensitive credentials. Check that in to your Git repository and you are good to go!
