### ISSUE TITLE
can we get all action(table/view/assertion) names in dataform schedule

### ISSUE THREAD

**Issue by Prempi** [dataform-co/dataform#1474]
can we get all action(table/view/assertion) names in dataform schedule by python coding or REST API or dataform CLI

**Comment by BenBirt** [comment]
I would suggest parsing the `environments.json` file as JSON.

**Comment by Prempi** [comment]
No, I mean in one schedule, it has several actions with success, failure, skipped etc. status after finish running, I want to get all the action name that has success status, because after the schedule was triggered, error log that sent via email(notification channels) only has the detail for failure action and we need to go to the run log's url to see the full details of all action status in schedule.

**Comment by BenBirt** [comment]
Ah, understood. Unfortunately we cannot support additions to the legacy Dataform product (and API) - we encourage you to try out GCP Dataform, and its API, which does include all of this information.
