### ISSUE TITLE
External contributors cannot pass the test commands in contributing.md

### ISSUE THREAD

**Issue by pokutuna** [dataform-co/dataform#1483]
This is a guide to run tests provided in contributing.md

https://github.com/dataform-co/dataform/blob/f58bbddf599ba1efe3c1d927213c3209a4b8681b/contributing.md#L35-L43

However, it fails with the following output:
```
ERROR: /home/pokutuna/dataform/test_credentials/BUILD:5:14: Action test_credentials/bigquery.json failed: (Exit 1): gcloud failed: error executing command external/gcloud_sdk/bin/gcloud kms decrypt '--ciphertext-file=test_credentials/bigquery.json.enc' '--plaintext-file=bazel-out/k8-py2-fastbuild/bin/test_credentials/bigquery.json' ... (remaining 4 arguments skipped)
 ERROR: (gcloud.kms.decrypt) PERMISSION_DENIED: Request had insufficient authentication scopes.
 - '@type': type.googleapis.com/google.rpc.ErrorInfo
   domain: googleapis.com
   metadata:
     method: google.cloud.kms.v1.KeyManagementService.Decrypt
     service: cloudkms.googleapis.com
   reason: ACCESS_TOKEN_SCOPE_INSUFFICIENT
```

This command runs all tests except those depending on secrets. But the tests under the `tests/cli/` also rely on Cloud KMS.
As a result, external contributors cannot run these tests.

This line is depending on a secret.
https://github.com/dataform-co/dataform/blob/f58bbddf599ba1efe3c1d927213c3209a4b8681b/tests/cli/BUILD#L17

**Comment by Ekrekr** [comment]
Thanks for pointing this out!
