### ISSUE TITLE
database() and schema() functions not working within sqlx files

### ISSUE THREAD

**Issue by pokutuna** [dataform-co/dataform#1484]
I've noticed that the database() and schema() functions, which were added in the following pull requests, cannot be used within sqlx files.

- #1432
- #1438

According to the document for `ItableContext` and `CommonContext`, these functions should be available for use within sqlx files.
> Context methods are available when evaluating contextable SQL code, such as within SQLX files, ...
- https://cloud.google.com/dataform/docs/reference/dataform-core-reference#itablecontext
- https://cloud.google.com/dataform/docs/reference/dataform-core-reference#commoncontext

These functions are not available in the latest version 2.4.2.

Are these functions intended for API-level use from core?
It would be helpful if these functions could be used from sqlx.

For BigQuery, the following use cases can be considered:
- Query usage with INFORMATION_SCHEMA in project(database) or dataset(schema)
- Check existence of table in dataset(schema) and branch processing

I will send a pull request to fix this issue shortly.

**Comment by a2wd** [comment]
Thanks for doing this, have merged your PR
