### ISSUE TITLE
Usage of the cmd+click feature

### ISSUE THREAD

**Issue by francis-cfc** [dataform-co/dataform#1509]
Hi All,

I am unable to use the cmd+click on a ref() capability in my vscode. I already ran npm i -g @dataform/cli. Are there other things I need to install/do to ensure that this works well?

**Comment by Mallington** [comment]
Looks like we have the same issue. Did you ever work out what the issue was?

**Comment by francis-cfc** [comment]
Nope... I think the vscode extension might be an outdated extension that doesn't get any attention at the moment.

**Comment by Ekrekr** [comment]
@GJMcGowan is best placed to fix this!

**Comment by francis-cfc** [comment]
Thanks @Ekrekr .

Hi @GJMcGowan can you please look into this as it will be save users a lot of time navigating to different dependencies every time in vscode. You can let us know when you pick this or tell us what to do to make this work.

Thanks mate.

**Comment by Ekrekr** [comment]
@Mallington debugged in https://github.com/dataform-co/dataform/issues/1556 that the error which occurs is

```
[Error - 23:54:48] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read properties of undefined (reading 'split')
  Code: -32603
```

**Comment by Ekrekr** [comment]
I believe this should have been fixed by https://github.com/dataform-co/dataform/pull/1769
