### ISSUE TITLE
dataform cli commands very slow for its runtime.

### ISSUE THREAD

**Issue by sukhamritboparai** [dataform-co/dataform#1511]
The dataform cli commands like dataform run --tags=xyz is really slow since couple of weeks. We saw it fluctuating over last few weeks from 10 minutes runtime to 40 minutes runtime for our project. Any help to resolve this will be really helpful. We are using GCP bigqury as well as dataform cli commands in our cicd i.e we cannot bypass using dataform.core or dataform cli usage. 
Thanks

**Comment by BenBirt** [comment]
`dataform run` runtime is really going to depend on how long it takes to execute your BQ jobs. Have you looked at your BQ job runtime / debugged why they are sometimes taking longer than expected?

**Comment by sukhamritboparai** [comment]
thanks for the response, We are running integration tests in our cicd by performing dataform run on bigquery empty tables, i.e no data at all just running "create or replace" on bq via dataform and have noticed the runtime increased to 70% for the same code.

**Comment by BenBirt** [comment]
Understood - but have you checked the BQ job runtimes, and verified that they are not the cause of the slowdown?

**Comment by sukhamritboparai** [comment]
yes, i [used](https://cloud.google.com/bigquery/docs/information-schema-jobs#query_the_list_of_long_running_jobs)  to quickly QA the runtimes and saw the longest query takes around 7secs on empty tables and there are not many like these in our project.

**Comment by sukhamritboparai** [comment]
we figured out the issue, it was apparently bigquery but not the speed of queries. Specifically the no of datasets/tables a bigquery instance can handle in each GCP project. It wont error out but definitely slows down the overall performance.
