### ISSUE TITLE
BigQuery incremental table now fails when REGEXP_EXTRACT() is used 

### ISSUE THREAD

**Issue by benjaminYakuto** [dataform-co/dataform#1514]
Info: 
- Bigquery
- Version: `2.6.0`

I have two separate `.sqlx` files that use some common code. To avoid repetition I use a `.js` file stored in includes. From today, one of the scripts when executed as part of a workflow has started failing. The error I'm seeing is: 

`reason:"invalidQuery" location:"query" message:"Syntax error: Illegal escape sequence: \\w at [176:61]": invalid argument`

In the `.js` file, the string corresponding to line 176 is: 

`(SELECT SAFE_CAST(REGEXP_EXTRACT(value.string_value, r"\\w+_\\w+_(\\d+)") AS INT64) FROM UNNEST(event_params) WHERE key = "bot_level")`

I understand using the raw string specifier and then double `\` to escape is incorrect; however, I do this because the output from the BigQuery side is:

`(SELECT SAFE_CAST(REGEXP_EXTRACT(value.string_value,r"\w+_\w+_(\d+)") AS INT64) FROM UNNEST(event_params) WHERE key = "bot_level") `

Only single backslashes are now present. This query runs successfully when performing a full refresh, or in an editor when run ad-hoc. It fails when an incremental refresh is performed. The only immediately obvious difference between the full refresh and incremental workflow code is the inclusion of the `EXECUTE IMMEDIATE` procedure, so I believe this might be a factor. 

Any help here would be appreciated.

**Comment by nsv-goog** [comment]
I have a similar scenario where I am using incremental type table and have used regex_extract for string manipulation. it fails if we don't use raw string. Any help would be appreciated. If this is the right way then please help document it for the developers

**Comment by Ekrekr** [comment]
Thanks for reporting this! It's clearly a bug - we're adding additional backslashes as part of the `EXECUTE IMMEDIATE` part:

![image](https://github.com/dataform-co/dataform/assets/13434377/d4c272d7-ee6d-4f3b-8b6c-63f080f808b6)

**Comment by Ekrekr** [comment]
From chatting with the team, the double escapes in the execute immediate block are needed because we don't use it as a literal `r"""` block (for other reasons).

We patched an issue with this double escaping soon after this issue was reported, which is probably what you were hitting - so whatever your user journey was, it should be working now! Feel free to re-open this issue if not.
