### ISSUE TITLE
When is the next release coming?

### ISSUE THREAD

**Issue by lucaviolanti** [dataform-co/dataform#1515]
The current one is affected by the following vulnerabilities
- CWE-1321 / https://github.com/advisories/GHSA-h755-8qp9-cq85
- CWE-1333 / https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

As far as I can see, both dependencies have already been upgraded by dependabot:
- https://github.com/dataform-co/dataform/pull/1507
- https://github.com/dataform-co/dataform/pull/1510

**Comment by BenBirt** [comment]
Published!
