### ISSUE TITLE
Built-in assertions for incremental tables always execute full scan

### ISSUE THREAD

**Issue by rhase** [dataform-co/dataform#1518]
It seems I can't add filter to built-in assertions.
So every time I execute built-in assertions, assertion query reads all patition.
So if I set requirePartitionFilter = true, assertion query fails.

I guess there should be an option to add filter to built-in assertions.
But views created under dataform_assertions don't need filter because you can write where caluse when you query the view.
Filters should only apply to assert statement.

**Comment by BenBirt** [comment]
I think this is *probably* too specific / out-of-scope for config-block assertions. I would suggest creating a "full" assertion, i.e. `type: "assertion"`.
