### ISSUE TITLE
Add in the ability to overwrite variables in Dataform.json when using Datafrom compile --json

### ISSUE THREAD

**Issue by seanovo** [dataform-co/dataform#1519]
We have our default database set as non-prod but would like to compile our project with references to prod, it seems you can overwrite variables but not those in Dataform.json - would it be possible to include these?

**Comment by BenBirt** [comment]
This definitely makes sense.

Would you be up for contributing this? It would be a pretty small change, just to https://github.com/dataform-co/dataform/blob/main/cli/index.ts; we'd need a new option following pretty much the same pattern as `schemaSuffixOverrideOption`.

**Comment by Ekrekr** [comment]
You can overwrite variables and all project config options as of https://github.com/dataform-co/dataform/pull/1454, LMK if this hasn't fixed your issue!
