### ISSUE TITLE
Dataform Compile CLI - Does not detect missing source declared in declarations

### ISSUE THREAD

**Issue by murlik1** [dataform-co/dataform#1529]
Hi Team,

The feature request is to extend the dataform compile to highlight **missing source tables declared in declarations**

In current case, dataform compile still goes ahead and successfully compiles the declaration even if the table declared is not existing, dataform does not actually check the resulting query to see if the table exists

This feature will help in adding CI checks by performing dataform compile.

Below is an example of declaration pointing to a non-existing table.

```
config {
    type: "declaration",
    database: dataform.projectConfig.vars.landing_project,
    schema:  dataform.projectConfig.vars.landing_dataset,
    name: "orders1"
}
```

This declaration when used in any table query, compiles without any issue. Ideally it should check the resulting query to check its validity.

**Comment by BenBirt** [comment]
Similar to https://github.com/dataform-co/dataform/issues/1530, Dataform does not perform SQL validation. If you want to do this, please `dataform run --dry-run`.

**Comment by murlik1** [comment]
Hi Ben,
Tried the same with dataform run --dry-run. The results are compiled successfully and does not actual validate the SQL generated.

```
config {
    type: "declaration",
    database: dataform.projectConfig.vars.landing_project,
    schema:  dataform.projectConfig.vars.landing_dataset,
    name: "orders1"
}
```

Compiled successfully.

Dry run (--dry-run) mode is turned on; not running the following actions against your warehouse:
```
8 dataset(s):
  structured_dataset.structured_customer_js_view [table]
  structured_dataset.structured_customers_incremental [table]
  structured_dataset.structured_customers_merge [table]
  structured_dataset.structured_customers_partitioned_merge [table]
  structured_dataset.structured_customers_scd2_updates [table]
  structured_dataset.structured_customers_scd2 [table]
  structured_dataset.structured_customers_table [table]
  structured_dataset.structured_shipments [table]
5 assertion(s):
  dataform_assertions.landing_customer_assertions_1
  dataform_assertions.landing_customer_assertions_2
  dataform_assertions.landing_shipment_assertions
  dataform_assertions.landing_orders_assertions
  dataform_assertions.structured_dataset_structured_customers_table_assertions_rowConditions
4 operation(s):
  structured_dataset.structured_customers
  landing_dataset.structured_shipments_truncate
  structured_dataset.structured_orders1. -----> This should have thrown compilation issue which depends on above declaration
  structured_dataset.structured_orders
```

please do have a check and let me know if the issue needs to be re-opened
