### ISSUE TITLE
Dataform - Error handling for incorrect variable usage in config block for database/schema configuration

### ISSUE THREAD

**Issue by murlik1** [dataform-co/dataform#1531]
In case when incorrect variable is used in the config block for database or schema declaration, it silently falls back to the values declared in dataform.json (defaultDatabase and defaultSchema).

Is this an expected behavior, the issue is due to silent behavior, the issue does not get caught until the code is run and table gets created in correct project or dataset.

Example of incorrect variable use. 
The below will not throw an compilation issue but go ahead with defaultDatabase value.

```
config {    
type: "incremental",    
tags: ["structured_customer"],    
dependencies: ["structured_customers"],    
database: dataform.projectConfig.vars.structured_projec,   -----> Incorrect variable but still compiles with defaulting to defaultDatabase
schema: dataform.projectConfig.vars.structured_dataset}

select * from ${ref("customers")}

${when(incremental(), `where ra_load_dte = current_date()`)}
```

**Comment by murlik1** [comment]
Any update on the above ?

**Comment by BenBirt** [comment]
I'm not sure about changing this behaviour, to be honest.

This is standard JavaScript behaviour, i.e. you've provided a value which evaluates to `undefined`, and as such the relevant property (`defaultDatabase` in this case) is considered to be unset.

In this particular case - `dataform.projectConfig` - we happen to own the object. We *could* wrap it in a `Proxy` which throws an `Error` on attempts to access `undefined` properties, which would catch this case.

But I'd be concerned that this would lead to confusing/mismatching behaviour, where this one object would act differently to all other JavaScript objects in user code. Users may end up confused and/or have wrong expectations about what we can/cannot enforce elsewhere in their project code.
