### ISSUE TITLE
Dataform Dry Run - Does not detect Incorrect SQL Syntax

### ISSUE THREAD

**Issue by murlik1** [dataform-co/dataform#1532]
This issue is linked to closed issue - https://github.com/dataform-co/dataform/issues/1530
The dataform run --dry-run command does not actually check the validity of the resulting compiled SQL.

Example
The below sample query has **from** misspelled as **fro**

```
config {
    type: "incremental",
    tags: ["structured_customer"],
    dependencies: ["structured_customers"],
    database: dataform.projectConfig.vars.structured_project,
    schema: dataform.projectConfig.vars.structured_dataset
}

select * fro ${ref("customers")} # incorrect SQL syntax - mentioned fro instead of from

${when(incremental(), `where ra_load_dte = current_date()`)}
```
```
Compiled 17 action(s).
8 dataset(s):
  structured_dataset.structured_customers_incremental [incremental]
```

The same can be extended to non-existing variable usage in transformations.

**Comment by BenBirt** [comment]
I'm surprised by this. I wonder if something is not being caught in https://github.com/dataform-co/dataform/blob/main/api/dbadapters/bigquery.ts#L105.

**Comment by KazuSh1geru** [comment]
The same problem is happening in my environment.

Using `dataform run --dry-run`, success response is coming. 
```sql: sample.sqlx
config {
  type: "table",
}

# incorrect SQL syntax - Does not exist "select"
  c.c_id,
  cu.cu_id,
  c.c_name,
  cu.role_id,
  c.in_house
from
  ${ref("customers", "company_users")} cu
  inner join ${ref("customers", "companies")} c ON cu.company_id = c.c_id

```

output
```
dataform run --dry-run
(node:30566) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:30566) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
Compiling...

Compiled successfully.

Dry run (--dry-run) mode is turned on; not running the following actions against your warehouse:

3 dataset(s):
```



Using `dataform run`, get expected results.

```
Dataset creation failed:  test_kusagi_dev.company_join_user [table]
  > create or replace table `lmi-sample-project.test_kusagi_dev.company_join_user` as 
  > 
  > 
  >   c.c_id,
  >   cu.cu_id,
  >   c.c_name,
  >   cu.role_id,
  >   c.in_house
  > from
  >   `sample-project.customers.company_users` cu
  >   inner join `sample-project.customers.companies` c ON cu.company_id = c.c_id
  bigquery error: Syntax error: Unexpected identifier "c" at [4:3]
```

**Comment by Ekrekr** [comment]
I've updated the dry run option to dry run the SQL against BigQuery https://github.com/dataform-co/dataform/pull/1698, which should solve this user journey. LMK if not!

**Comment by Ekrekr** [comment]
Hi Sergio,

It does execute the code - but as dry run, which never has any cost for the user https://cloud.google.com/bigquery/docs/running-queries#dry-run.

We can't test whether the SQL you have written locally is valid, it has to be sent to BigQuery for validation, and dry run is their mechanism for doing that.

So yes, it's expected that there will be jobs in the BQ logs!
