### ISSUE TITLE
dataform format fails on case/between statements

### ISSUE THREAD

**Issue by spatel11** [dataform-co/dataform#1539]
The following Definition

```sql
config {
  "type": "table"
}

SELECT CASE 
        WHEN 1 BETWEEN 2 AND 3 THEN 'test1'
        ELSE 'test2'
        END
```

Will result in a formatting error:
```
definitions/Between.sqlx: Unable to format "config {
  "type": "...".
```
when `dataform format` is run.
I'm using the `bigquery` warehouse type, but other types that I tried (`redshift`, `snowflake`) also failed on this definition.

The definition does compile however, and it's a valid query (at least according to `bigquery`)

An alternative formulation:
```sql
config {
  "type": "table"
}

SELECT CASE 
        WHEN 1 >= 2 AND 1 <= 3 THEN 'test1'
        ELSE 'test2'
        END
```
formats successfully.

**Comment by Ekrekr** [comment]
I think this is a bug in the SQL formatter that we use - and the error it gives isn't very helpful for that.

I'm in the process of open sourcing the GoogleSQL definition and formatter, to replace the current SQL formatter, which should fix this! If not, I'll take a look then.
