### ISSUE TITLE
Output incremental versions of queries in `dataform compile --json`

### ISSUE THREAD

**Issue by howyp** [dataform-co/dataform#1544]
I've noticed that for incremental tables, when running `dataform compile --json`, the `query` property shows the non-incremental version, ie. the query generated when `incremental() == false`.

Is there a way to output the incremental version? ie. the query generated when `incremental() == true`? 

If not, it would be really helpful if it could be added as an extra property in the JSON, or there be a flag in the CLI to indicate the incremental versions should be generated?

Thanks!

**Comment by BenBirt** [comment]
I believe that you should find the incremental version of the query in `incrementalQuery`.
