### ISSUE TITLE
Dataform requires secret access for Default Service Account even if not using Default Service account

### ISSUE THREAD

**Issue by justinaugust** [dataform-co/dataform#1566]
When setting up a repo to run using a separate Service Account, Dataform still requires secret access to be given to the default service account. This seems non-ideal.

**Comment by Ekrekr** [comment]
Hi Justin,

IIUC this is an issue with Dataform in GCP - could you re-file it in https://b.corp.google.com/issues/new?component=1193995&template=1698201 please?

Some more details on where you're hitting permissions errors when the default service account doesn't have secret access would help. Everything should be configured to use the service account that you set.

Thanks,
Elias

**Comment by Ekrekr** [comment]
From chatting with Ben, the P4SA is always configured to chat with secrets.

You're right that this is a bit weird, but it's how it was launched - so please do file a bug under https://b.corp.google.com/issues/new?component=1193995&template=1698201 if it is affecting you!
