### ISSUE TITLE
Empty pre/post operations should not throw an error for incremental tables

### ISSUE THREAD

**Issue by dawidczerwinski-eagleeye** [dataform-co/dataform#1569]
Related issue: https://github.com/dataform-co/dataform/issues/942

The following code provides different results depending if the table is incremental or not:
```
config {
    type: "incremental",
    hermetic: true
}
pre_operations {}
SELECT 1 AS test
post_operations {}
```

1) Non-Incremental - Correct Behaviour
![image](https://github.com/dataform-co/dataform/assets/104431104/1627e4e0-350d-4249-b421-3dfc726d263a)

2) Incremental - Unexpected Behaviour
![image](https://github.com/dataform-co/dataform/assets/104431104/f9fb4ad9-4712-4ffb-9e51-d29e9636ac11)

Just like in the mentioned related issue, this is invalid SQL for the Incremental Tables, and makes it hard to programmatically control pre/post options using e.g. `when()` statements for incremental.

**Comment by Ekrekr** [comment]
Hi Dawid,

Because this is for the Dataform UI, can you re-file it in the GCP issue tracking system? We use GitHub just for open source issues.

https://b.corp.google.com/issues/new?component=1193995&template=1698201

Thanks,
Elias

**Comment by Ekrekr** [comment]
I think there's a simple internal fix for this anyways, will submit a code change!
