### ISSUE TITLE
Logging does not log successful runs

### ISSUE THREAD

**Issue by justinaugust** [dataform-co/dataform#1572]
We are unable to push `SUCCESS` alerts to Notification Channels because currently the logging does not write logs for `SUCCESS` runs.

**Comment by BenBirt** [comment]
Hi Justin - if this is an issue for legacy Dataform, please note that it is maintenance-mode-only.

If this is an issue for GCP Dataform, please follow instructions at https://cloud.google.com/dataform/docs/get-support#file_bugs_or_feature_requests.
