### ISSUE TITLE
Current UX Has no ability to disable WorkFlow configurations

### ISSUE THREAD

**Issue by justinaugust** [dataform-co/dataform#1573]

**Comment by BenBirt** [comment]
Hi @justinaugust, thanks for filing this issue. However, this GitHub repository really just covers the open-source components of Dataform - if you want to file issues against Dataform in GCP, please https://cloud.google.com/dataform/docs/get-support#file_bugs_or_feature_requests.

For this particular issue, I think we already have a feature request filed: https://issuetracker.google.com/issues/294002978
