### ISSUE TITLE
Bazel fails to build the project on Apple silicon processors

### ISSUE THREAD

**Issue by claydiffrient** [dataform-co/dataform#1593]
When doing a few recent contributions, I was unable to build the project on my normal M1 Macbook and instead had to use an older Intel Mac to run the build.

The error I received was:
```
ERROR: ~/dataform/sandbox/vm/BUILD:42:14: While resolving toolchains for target //sandbox/vm:compile: no matching toolchains found for types @build_bazel_rules_nodejs//toolchains/node:toolchain_type
ERROR: Analysis of target '//cli:cli' failed; build aborted:
```

I believe that updating to a newer version of rules_nodejs will fix it similar to [this issue](https://github.com/bazelbuild/rules_nodejs/issues/2733).

Sadly, I don't have the bandwidth to do such an upgrade at the moment, but wanted to at least make sure there was an issue filed in case someone else can do it.

**Comment by ashish10alex** [comment]
Having the same issue when trying to build using Bazel on M2 Mac.
I tried updating the config but ended up in dependancy hell 
![CleanShot 2024-02-22 at 13 07 55@2x](https://github.com/dataform-co/dataform/assets/34306898/04d3ec62-7021-4367-babf-b4fa8dfadd7d)



 Would highly appreciate if someone could update the WORKSPACE config required to make this work on Apple Silicon.

**Comment by Ekrekr** [comment]
I think a bunch of our dependencies are older than the release of the M1 instruction set 😅 so this is unsurprising.

Bumping our dependencies will probably fix that, but that's a fairly painful process. It's already on the radar though, so this may be fixed in the next couple months.
