### ISSUE TITLE
Feature Request: a "retry" button on the schedules log page to run again

### ISSUE THREAD

**Issue by joaovictor-dito** [dataform-co/dataform#1600]
It would be more productive to have a button that allows the failed schedule to run again

**Comment by Ekrekr** [comment]
Hi João,

Because this is a bug for the Dataform UI, can you re-file it in the GCP issue tracking system? We use GitHub just for open source issues.

https://b.corp.google.com/issues/new?component=1193995&template=1698201

Thanks,
Elias
