### ISSUE TITLE
CRITICAL SECURITY ISSUE: vm2 should bee replaced by isolated-vm

### ISSUE THREAD

**Issue by vl4py** [dataform-co/dataform#1615]
## Description

vm2 is sensible to [sandbox escape attack](https://github.com/advisories/GHSA-g644-9gfx-q4q4). Since 3.9.19 the project is now discontinued. The main contributor recommand to migrate to isolated-vm.

**Comment by BenBirt** [comment]
Thanks. We are aware of the issue.

Currently we do not use `vm2` to implement any sandbox/secure computation features. It's now just used as a way to easily execute JavaScript in the way that we need to do implement compilation.

We will replace it at some point.

**Comment by vl4py** [comment]
Thank you for the quick reply

**Comment by oikarinen** [comment]
@BenBirt any update on this?

**Comment by BenBirt** [comment]
No - as above, we do not use `vm2` to implement any security boundary. We'll replace it, but that's at low priority.
