### ISSUE TITLE
Syntax highlighting breaks on regular expression

### ISSUE THREAD

**Issue by dragonlobster** [dataform-co/dataform#1625]
Dataform GCP syntax highlighting is very buggy and problematic. Just one simple example, it breaks the moment you add any regular expression:

```SQL
select REGEXP_REPLACE(JSON_QUERY(a.json_field, "$.jsonKey"), r'([\'\"])', '') as VALUE
FROM table a
WHERE a.some_field > 1;
``` 
This is a screenshot from the GCP editor for Dataform:

![image](https://github.com/dataform-co/dataform/assets/63202668/f7c0f5b6-0eac-47f9-a08c-e94b0f509d3e)

Even markdown syntax highlighting gets it right where as dataform can't.

_Originally posted by @dragonlobster in https://github.com/dataform-co/dataform/issues/1589#issuecomment-1867137197_

**Comment by Ekrekr** [comment]
> Even markdown syntax highlighting gets it right where as dataform can't.

Not sure that's true! As SQLX is a DSL that's neither SQL or javascript, it would be very surprising if any markdown interpreters supported it.

Please file this under the tracker for issues for the web https://cloud.google.com/dataform/docs/get-support#file_bugs_or_feature_requests, as it's not relating to open source directly.
