### ISSUE TITLE
Materialized views in Dataform  using partitions and clusters seems that they are not supported

### ISSUE THREAD

**Issue by nicolasrodriguez-mb** [dataform-co/dataform#1666]
In a SQLX, I am trying to create a materialized view like:

config {
    type: "view",
    materialized: true ,
    bigquery: {
        partitionBy: "partition_date",
        clusterBy:  ["col1", "col2"]
    }
}

But it seems it is not supported, it shows a message

"partitionBy/clusterBy/requirePartitionFilter/partitionExpirationDays are not valid for BigQuery views; they are only valid for tables"

**Comment by BenBirt** [comment]
Good news - this is now supported in `2.9.0`: https://github.com/dataform-co/dataform/releases/tag/2.9.0

**Comment by nicolasrodriguez-mb** [comment]
Thank you
