### ISSUE TITLE
Unable to join slack group

### ISSUE THREAD

**Issue by JamesAPetts** [dataform-co/dataform#1701]
I can't join with a gmail (by logging in with google).

This was also reported in issue #1253, but I'm getting the same issue and the solution is not working for me.

![Screenshot 2024-03-28 at 09 17 49](https://github.com/dataform-co/dataform/assets/25818497/7776bc4c-a061-4c86-b598-14e3ca1184bb)

**Comment by Ekrekr** [comment]
Slack group is no longer running - support page for the new product: https://cloud.google.com/dataform/docs/get-support
