### ISSUE TITLE
For inline assertions: uniqueKeys is broken, uniqueKey works, we should just remove uniqueKeys

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#1717]
UniqueKeys throws `t.join is not a function`.

It happens because indexAssertion is called with a string, rather than a list of strings https://github.com/dataform-co/dataform/blob/754d582f4f588b3c812c40a38ec839607ec3d4f0/core/actions/table.ts#L642.

It's documented as supported.

As a workaround, users are likely just using `uniqueKey`, which supports both.

We should just remove `uniqueKeys`, in favour of `uniqueKey`.

![image](https://github.com/dataform-co/dataform/assets/13434377/258d34a5-f3e6-41eb-9876-7d027d9331f4)

**Comment by BenBirt** [comment]
In addition - the reason we added `uniqueKeys` is because users wanted to define >1 unique key function.
