### ISSUE TITLE
Please release a 3.0.0 docker image

### ISSUE THREAD

**Issue by IzakMaraisTAL** [dataform-co/dataform#1771]
Dataform 3.0.0 has been released, but the latest dockerhub image tag is 3.0.0-beta1. Please update this.

**Comment by lveraszto** [comment]
+1

**Comment by IzakMaraisTAL** [comment]
Related ticket: https://issuetracker.google.com/issues/349291136?pli=1 

> Apparently docker version is no longer being supported - and we are advised to create our own using node docker image and the dataform npm package

**Comment by Ekrekr** [comment]
We've had to stop publishing new docker images due to some security requirements.

I'd recommended just building your own image for it as part of your CI/CD, for example by creating the DOCKERFILE:

```DOCKERFILE
# syntax=docker/dockerfile:1

FROM node:18-alpine
RUN  npm i -g @dataform/core@3.0.0
RUN dataform compile
```

and then running

```bash
$ docker build .
```

Let me know if this works for you!

**Comment by IzakMaraisTAL** [comment]
Thanks for the feedback.
