### ISSUE TITLE
Dataform 3.0.0-beta4 is buggy when compiling and often throws uncaught @dataform/core error.

### ISSUE THREAD

**Issue by Et9797** [dataform-co/dataform#1801]
Thought something was wrong with my queries initially, but after changing back to 3.0.0 they all worked fine, and the Run button showed back up. Why is a beta version default when starting a project, anyways?

Cheers for the great project.

**Comment by Ekrekr** [comment]
I've updated the default in the GCP app to be `3.0.0` now!
