### ISSUE TITLE
[Enhancement] Support Github Apps as authentication method when linking to Github repositories

### ISSUE THREAD

**Issue by penenkel** [dataform-co/dataform#1807]
I would like to use a Github App to establish the authentication when linking Dataform to a Github repository.

At the moment only PATs are supported. Personal access tokens are by definition bound to a person whereas the Dataform-Github connection is more of the machine-to-machine kind. Also, Github only allows the repository owner to generate PATs for it. A third downside to using PATs is that they are comparatively long-lived secrets.

(Ab-)using a separate user account as a service account is no longer recommended by Github (also such an account is subject to licencing-fees). Github recommends "Github App"s for third party service integrations.

**Comment by Ekrekr** [comment]
We have an open issue for this in the public issue tracker, so closing as duplicate b/304522016

**Comment by penenkel** [comment]
@Ekrekr Are you certain that that issue tracker is public? It's asking for a login with a google.com account.

**Comment by penenkel** [comment]
ah the correct link is https://issuetracker.google.com/issues?q=%20304522016
