### ISSUE TITLE
BUG view + assertion uniqueKey on dataform v3.0.2

### ISSUE THREAD

**Issue by AntoineGiraud** [dataform-co/dataform#1835]
Hi,

Since dataform v3.0.2
With a view, and a `uniqueKey` assertion, it doesn't take my column name but puts `TableAssertionsConfig` instead in the SQL assertion

after some trial, it works fine :
- as is on v3.0.0
- on a table + uniqueKey & v3.0.2
- on a view + uniqueKey**s** & v3.0.2

At your service to provide more details on this issue :)
Antoine

recap img on the subject
![image](https://github.com/user-attachments/assets/4dc83869-d216-4a2b-95dc-632417c05d61)

**Comment by alejandro-delgado-garcia** [comment]
it also does the same thing with incremental tables

**Comment by AntoineGiraud** [comment]
Resolved with [3.0.7](https://github.com/dataform-co/dataform/releases/tag/3.0.7) 🥳 Thanks !
