### ISSUE TITLE
Add documentation to cover the --schema-suffix flag

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#228]
We should document the schema suffix flag 
- [ ] What it is used for
- [ ] How to use it

**Comment by canetcesc** [comment]
Hi @lewish, I am taking issue #307 now (pull request #323 ).
Is this issue only related to CLI help? If so, I can piggyback the changes on that one.
Could you explain what to put down on the CLI  next to the `--schema-suffix` option of the `dataform run` command? - I don't know what is the meaning of this flag!
