### ISSUE TITLE
Implement tags for actions

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#229]
All action types, datasets, operations, and assertions - should carry a list of tags that can be added to that action type.

Tags are simply a list of string labels that can be added to an action. These will be used for specifying schedules in the future.

For example, with the new configuration syntax:

```
config {
  tags: ["tag1", "tag2"]
}
```

**Comment by BenBirt** [comment]
This would involve:
1. Adding a new `tags` property on the `ISqlxConfig` interface, giving it a default value of `[]` at https://github.com/dataform-co/dataform/blob/master/core/compilers.ts#L92, and passing it through to the dataset/operation/assertion here: https://github.com/dataform-co/dataform/blob/master/core/session.ts#L56
2. Defining a new field on the relevant protobuf messages (`Table`, `Operation`, and `Assertion`) here: https://github.com/dataform-co/dataform/blob/master/protos/core.proto, and populating it with the result of (1)
3. For bonus points, extending the JS API to allow users to specify this, by defining new `tags()` methods on `Table`, `Operation`, and `Assertion` (all in the `/core/` directory).

**Comment by faiyaz26** [comment]
One PR on this issue: https://github.com/dataform-co/dataform/pull/304

**Comment by BenBirt** [comment]
fixed with https://github.com/dataform-co/dataform/pull/304

**Comment by canetcesc** [comment]
Please reopen this issue or open a new one to include code that can resove what graph actions to run. Ping @BenBirt
