### ISSUE TITLE
Implement SQL unit tests for dataset queries

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#230]
It should be possible to write a unit test for a dataset query, where mocked data can be provided as input in place of any referenced datasets, and an expected result is also provided.

Awaiting a design doc, will update.

**Comment by andrewscarani** [comment]
@lewish Is it possible to specify multiple mocks/inputs? And if so, how would one do this?

**Comment by BenBirt** [comment]
Hopefully it's all clear in https://docs.dataform.co/guides/tests, but yes it is possible to specify multiple named inputs.

**Comment by andrewscarani** [comment]
@BenBirt It is not clear, because there are not any examples of multiple named inputs in that guide and we've tried a few things that did not seem to work. Do you have a working example?

**Comment by ryanlim48** [comment]
@BenBirt Andrew and I figured out that a semicolon is needed between inputs just by testing out random syntax. It may be helpful to include this in the docs in case others may be running into a similar issue

**Comment by BenBirt** [comment]
That is completely unexpected, apologies. I've filed https://github.com/dataform-co/dataform/issues/1351
