### ISSUE TITLE
Changing the number of columns in a view definition causes an error in Redshift

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#259]
Getting error: "cannot change number of columns in view"

To reproduce in Redshift:
 - Create new file "SELECT 1 as one, 2 as two"
 - Run action
 - Replace statement with "SELECT 1 as one"
 - Run action again and get the error

---
Moved from dataform-co/dataform-co#663
/cc @G2H

**Comment by dwl285** [comment]
This error still happens for assertions:
![image](https://user-images.githubusercontent.com/4967152/72454038-096efc00-37b8-11ea-9514-2919c23ffa7a.png)
