### ISSUE TITLE
CLI run output sometimes has missing actions

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#266]
I'm pretty sure that this happens because at the end of the command we don't check to make sure that `alreadyPrintedActions` includes all items in `actionsByName`. After awaiting the result, we should finally print out any unprinted action names.

**Comment by dwl285** [comment]
@benoitfayolle for tracking

**Comment by BenBirt** [comment]
@BenoitFayolle if you upgrade your version of the `@dataform/cli` package to 1.0.0-alpha.2 (I just published it), hopefully you can confirm this bug is fixed for you!
