### ISSUE TITLE
Add some documentation and examples of the resolve function in the docs

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#277]
The resolve function `${resolve("tablename")}` is not documented. Resolve is the same as ref but it doesn't add any dependencies.

We should add an example of the resolve function under the Operations guide, as it is useful for them.

**Comment by dwl285** [comment]
@lewish what makes resolve useful in operations?

**Comment by BenBirt** [comment]
https://docs.dataform.co/guides/built-in-functions/
