### ISSUE TITLE
Implement tag filtering in Builder

### ISSUE THREAD

**Issue by canetcesc** [dataform-co/dataform#316]
Related to Issue #229.

This would let you actually use tags when running (on the CLI for now). It would mean changing the RunConfig protobuf to include a list of tags to run, and then using that list inside the Builder code.

**Comment by canetcesc** [comment]
I accidentally pushed the “create pull request” button. I only wanted to push the “create draft pull request”. So no code review needed yet.

**Comment by canetcesc** [comment]
Can you help me clarify if the expected behavior in the cases marked bellow in yellow is correct?

![Screenshot 2019-07-22 at 14 02 26](https://user-images.githubusercontent.com/44415335/61630957-5c447c80-ac89-11e9-87ce-cdec6b8992e6.png)

**Comment by canetcesc** [comment]
Typo: Should be *upstream* dependencies (what comes *before*).

**Comment by BenBirt** [comment]
LGTM! Thanks for checking!
