### ISSUE TITLE
Support for Athena/Presto

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#330]
Athena is quite different from the existing warehouses we support and will require a few more settings to be added, e.g setting s3 file locations.

https://aws.amazon.com/athena/

- [ ] Write an AthenaDBAdapter
- [ ] Write an AthenaAdapter
- [ ] Add documentation for athena specific settings
- [ ] Add Athena integration tests

**Comment by rbalsick** [comment]
Do you have any updates on when this might be worked on? I would like to introduce Dataform to my new team here at Saatva but we use Athena for our data warehouse and this is a big hurdle to me being an advocate!

**Comment by brucemen711** [comment]
Hi @lewish, do you have any plan on this ?

**Comment by boristyukin** [comment]
no interest?

**Comment by Ekrekr** [comment]
We're not currently working on this. However, there is part of an integration checked in; the API used is missing [various features](https://github.com/dataform-co/dataform/blob/master/api/dbadapters/presto.ts), with [tests laid out here](https://github.com/dataform-co/dataform/blob/master/tests/integration/presto.spec.ts).
