### ISSUE TITLE
Includes in subfolders don't get automatically exported

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#333]
An includes file in a subfolder such as:

```
includes/folder/utils.js
```

Doesn't get exported into the global namespace, and can't be referenced without using explicit imports.

Offending line seems to be here: https://github.com/dataform-co/dataform/blob/master/api/vm/gen_index_config.ts#L10

We could expand this glob expression to be recursive, which will also require filenames within includes/ to be unique.

**Comment by BenBirt** [comment]
Let's talk about this!

**Comment by BenBirt** [comment]
After discussion, closing this because it would require that users have unique `.js` filenames everywhere in `includes`. I have opened https://github.com/dataform-co/dataform/issues/338 to track being able to fully-specify `require` paths.
