### ISSUE TITLE
Projects with operations only will output an error when starting a new run

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#345]
On Redshift (and possibly PG and Snowflake)

Returning error:
error: cannot execute CREATE SCHEMA in a read-only transaction

And no operation is run

I assume dataform tries to create a schema befiore executing any query

---
Moved from dataform-co/dataform-co#1098
/cc @G2H

**Comment by G2H** [comment]
I confirm I can't reproduce this anymore
