### ISSUE TITLE
Add compile time validation warnings for dataform.json

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#346]
Had entered dataform instead of bigquery for the warehouse, didn't get any error message pointing in the right direction

---
Moved from dataform-co/dataform-co#134
/cc @G2H

**Comment by canetcesc** [comment]
@BenBirt - Basides defaultSchema and warehouse, do we need to check for warehouse-specific required properties? See list:

```
const requiredBigQueryWarehouseProps: Array<keyof dataform.IBigQuery> = [
  "projectId",
  "credentials"
];
const requiredJdbcWarehouseProps: Array<keyof dataform.IJDBC> = [
  "host",
  "port",
  "username",
  "password",
  "databaseName"
];
const requiredSnowflakeWarehouseProps: Array<keyof dataform.ISnowflake> = [
  "accountId",
  "username",
  "password",
  "role",
  "databaseName",
  "warehouse"
];
const requiredSQLDataWarehouseProps: Array<keyof dataform.ISQLDataWarehouse> = [
  "server",
  "port",
  "username",
  "password",
  "database"
];
```

**Comment by BenBirt** [comment]
Those are properties that must go in the `credentials` JSON file, not `dataform.json`. We should only need to check fields as exist in the `ProjectConfig` protobuf.
