### ISSUE TITLE
Overwriting schema name doesn't seem to work when using the JS api

### ISSUE THREAD

**Issue by G2H** [dataform-co/dataform#357]
`publish(my_table).config({type: "table", schema: "test_schema"}).query("SELECT 1 as one")` creates a new table on the defaultSchema

**Comment by canetcesc** [comment]
I’ll take a look and add a new test case in`api.specs,ts` as this is anyway related to what I’m doing on #280.

**Comment by G2H** [comment]
That was quick, thanks Cesc!

**Comment by canetcesc** [comment]
Included in release `1.2.3`
