### ISSUE TITLE
Document open-source contribution process

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#364]
We should add some stuff to contributors.md. Something like:

- when opening a PR, feel free to immediately request a review, probably from @BenBirt or @lewish
- one reviewer is fine, add two or more though if you want to get something in faster / want more eyes reviewing
- after resolving a round of PR comments, hit the "re-request review" button
- once the PR is approved & you have resolved any final comments, ping your reviewer (probably on Slack? or Intercom?) asking for them to run the integration tests & merge the PR if they pass

**Comment by Ekrekr** [comment]
Requirement for `env.yaml` and how to access should be added.

* Download and install [GCloud](https://cloud.google.com/sdk/docs/quickstarts).

* `$ gcloud init`, log in.

* `$ gcloud config set project tada-analytics`

* `$ ./scripts/decode_credentials`

**Comment by Ekrekr** [comment]
Partially fixed in PR #523

**Comment by faiyaz26** [comment]
@Ekrekr the commands you provided are not really helpful for the open source developers it is more of dataform-co thing.

**Comment by Ekrekr** [comment]
@faiyaz26 Ah I see, it's been changed again in PR #537 with the documentation rebase, but the commands haven't changed much. Should there be more info on developing packages do you think?
