### ISSUE TITLE
Create a way to override project level settings via the command line

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#381]
Currently there is no way to override project level settings for compilation or runs.

This would be extremely useful for integration tests and examples, where we will probably have a single project that will be valid across all warehouse types for simple operations.

Rough proposal:
- Add a flag such as `--config` that accepts a blob of json that effectively overrides the contents of dataform.json for that project.
- Merge these settings into the object produced from the dataform.json file when we compile.

I'd argue this could be a good general mechanism for flags controlling runs. If the user wants to add settings to the dataform.json file that extend it, then rely on those values in scripts, this would be a simple way to do that, and would allow setting e.g. project level constants in the dataform.json file.

**Comment by BenBirt** [comment]
I propose that - at least for now - we don't expose this in the CLI, but instead make it possible to do in the `compile()` API. To do that we can extend `CompileConfig` to have a `ProjectConfig` field which, if set, overrides `dataform.json`. (I would propose *not* doing the merge as IMO that may be more confusing than doing it.)
