### ISSUE TITLE
Redshift error details sometimes not included in queries

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#422]
Redshift seems to split errors into the top level error and then additional details. These additional details don't get propagated anywhere, and leaves some high level messages such as the following that are hard to debug:
```
Assert
deadlock detected
```

Additionally, it appears line/column number information is available, but we don't show it.

We should look at all the fields that redshift errors might have and make sure they get added to the overall error message.

**Comment by BenBirt** [comment]
dup of https://github.com/dataform-co/dataform-web-tracking/issues/170
