### ISSUE TITLE
Warehouse integrations page appears to have no content

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#536]
Warehouse integrations page has no content
![Screenshot 2019-12-23 at 10 51 17](https://user-images.githubusercontent.com/13434377/71353884-3b52c100-2572-11ea-93c1-0565106d6c0a.png)

**Comment by Ekrekr** [comment]
Subpages do have content. Would be worth describing why integrating is so useful, etc. I'll fix this when I add documentation on SQLX

**Comment by Ekrekr** [comment]
Also [version control page](https://docs.dataform.co/platform_guides/version_control) gives a 500 error.

**Comment by BenBirt** [comment]
We're about to redo all of the docs, so closing this for now.
