### ISSUE TITLE
Move validation into a standalone operation

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#59]
Currently validation happens in a number of different places, during compilation, but also during API calls to the core framework.

As a result, it's hard/impossible for the other parts of the library to validate a graph (for example, if we want to run validation before we build or run a graph).

We should untangle the current validation code into a single methods that takes a CompiledGraph proto and adds returns a copy with validation errors added appropriately.

**Comment by ShevtsovY** [comment]
summarize:

1.move compilationErrors from Graph to GraphErrors (GraphErrors will store in Graph)
2.remove validationErrors from Graph
3.remove validationErrors from Table
4.during the compilation process we will create only compilationErrors
5.during the compilation process we will NOT do any validation checks
6.add validate() function to utils, which will return GraphErrors:
```{
  compilationErrors, // from Graph
  validationErrors   // check Graph and Tables
}```
