### ISSUE TITLE
Some CSS in docs is a bit iffy

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#592]
For example, spacing between headers isn't consistent due to a combination or margins and padding. Could do with some standardisation.

![image](https://user-images.githubusercontent.com/13434377/73740689-90245280-4740-11ea-9570-d8760336c7c9.png)

**Comment by lewish** [comment]
Thanks Elias - for the purposes of triage I'm going to close this for now as it's relatively minor, please do feel free to send a PR though!
