### ISSUE TITLE
BigQuery sometimes fails with "Error encountered during execution. Retrying may solve the problem"

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#616]
This is less than ideal, and appears to affect some users more than others.

Given that BigQuery is basically telling us this is probably their fault, I think it would be safe for us to retry a few times if we see this specific error message.

**Comment by paddie** [comment]
@lewish  We are hit by this quite a lot. Is there any hope of solving this inside dataform or do we need to do some automatic re-triggering on our end when this happens?
