### ISSUE TITLE
No way to access environment name from inside SQLX

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#617]
This goes along with exposing other potentially useful fields.

A potential solution to this is adding `environmentName` to the `projectConfig` proto, and shortening access to the global session config.

Currently available:

```
select ${global.session.config.warehouse} as warehouse
```

Could be available:

```
select ${projectConfig.environment} as warehouse
```

**Comment by justinaugust** [comment]
Was this ever implemented?
