### ISSUE TITLE
Redshift: Don't attempt to create schemas if they already exist

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform#689]
Some users (especially when first evaluating Dataform) prefer to give strict permissions to the redshift user, only allowing Dataform to modify data within a specific schema. They first create a schema (e.g. `scratch`) outside of Dataform, and then modify `dataform.json` to point only to that schema.

Because we run the command `create schema if not exists "${schema}"`, run creation fails (even though the schema doesn't actually need to be created).

This issue has caught out at least two users in the past.

**Comment by BenBirt** [comment]
dup of https://github.com/dataform-co/dataform/issues/397
