### ISSUE TITLE
Don't show the "email not verified - contact me for help" toasted on the "verify your email address" page

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform#691]
When users first sign up for a Dataform account (using email/password) we show them a "verify your email address" page. There is also a toaster saying "Error: Email not verified" that pops up. This is duplicative an looks buggy, we should stop showing this toaster on this page.

STR:
- Create a new account (username + password)

ER:
- Land on verify your email address page (no toaster)

AR:
- Land on verify your email address page *and* receive a warning toaster

**Comment by BenBirt** [comment]
Moved to dataform-co/dataform-co#5141
