### ISSUE TITLE
API adapter for operations should limit the number of queries performed

### ISSUE THREAD

**Issue by Ekrekr** [dataform-co/dataform#814]
If someone creates an operation that will perform over a thousand operations on their warehouse, this should just not be allowed. It will cost them excessive amounts, and there will always be a better way of defining it.

Proposed limit: 10?

**Comment by BenBirt** [comment]
What's the motivation here? We wouldn't be stopping the user from creating just as many operations files, so I'm not sure what the win is aside from forcing them to express the same thing in a different way.

**Comment by Ekrekr** [comment]
If someone's using a crazy amount of operations, there's a good chance they're just constructing a table by inserting row after row, which ends up being expensive (we've seen cases with over 4000 operations). @dwl285 says he can't think of a situation where it wold ever be beneficial to have more than roughly 10 operations, so this would be a way of forcing users into not wasting money by making them think of a better way to do a set of operations.

Perhaps an overridable flag in the config block would handle this well, in case a user did want more operations?

**Comment by BenBirt** [comment]
Right, I do agree that if the user does this, then there is high likelihood they are doing something wrong, but I don't buy that we should be implementing this in the language. There's lots of things that are strong indications that the user is doing something wrong (e.g. even using `operations` at all is a very strong indicator), but IMO it's not up to the language to capture all those cases. The right place to do it is in the UI/editor, which AFAIUI we now do.
