### ISSUE TITLE
Run caching should not store input-last-modified timestamps taken at the *end* of a run for inputs that the run did not itself write

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#860]
Consider this case:

Declaration A
Table B (depends on A)

At the start of the run, A's last-modified timestamp is 100; at the end of the run, A's last-modified timestamp is 200. B may have read data from it at any timestamp between 100 and 200.

Currently, run caching will store a cache entry for B, saying that it has one transitive input A, and that the last-modified timestamp for A was 200 (because it fetches these timestamps at the end of the run).

However, this isn't correct, because B may not have read data up to timestamp 200. Instead, we should be storing a last-modified timestamp for A of 100, because we know that B read _at least_ up to timestamp 100.

This holds for all inputs that are not themselves written during the course of a run: the last-modified timestamp for such an input should be taken from the *start* of the run, not the end.

**Comment by lewish** [comment]
SGTM
Out of interest, if there is a third table C that reads B, what last-read timestamp will we store? (assuming B was also written during this run).

Sounds like this has the same problem except it's less likely to happen, as B could only be written by Dataform, and this would only cause issues if you had two overlapping runs. In an ideal world we should be working out the last-updated-ts for B immediately after publishing B, before running C, and use that.

**Comment by BenBirt** [comment]
In C's cache entry, we'd store a timestamp for B recorded at the end of the run. I think that remains semantically correct - Dataform requires the invariant that it "owns" the tables it's writing during the course of a run; if that invariant breaks, all bets are off.

However, changing the behaviour to record the timestamp immediately after writing the table isn't incorrect, and may make the code easier to follow, so this may be what we end up with.

**Comment by lewish** [comment]
I'm not necessarily convinced that we should assume that Dataform get's a lock on the action for the duration of the run, there's not much stopping this happening currently. However as you say I think we can resolve this issue when/if we run into it!

A lot of this code would be easy to write if we could trust system time of whatever we are running on. I wonder if there are libraries or ways we can get consistent system times in these code paths (just a thought for the future).

**Comment by BenBirt** [comment]
IMO trying to reason about Dataform *not* having a lock on all affected tables during a run gets really difficult really quickly. Having no way of knowing whether the last modification to a table was _the query DF just ran_ or _something else_, we can make no guarantees of correctness, unless we do make this assumption.
