### ISSUE TITLE
Schema suffix and table prefix options are not upper-cased in Snowflake

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#941]
We uppercase all action names in snowflake as snowflake does this itself, however we don't uppercase the schema suffix.

This leads to weird looking action names, e.g:

`DATABASE.SCHEMA_suffix.prefix_TABLE_NAME`

We should be consistent and uppercase the full action name, including both schema suffix and prefix in Snowflake only.

**Comment by BenBirt** [comment]
dup of https://github.com/dataform-co/dataform-co/issues/7575
