### ISSUE TITLE
Formatting of regexps with $ characters changes code

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#988]
For example, formatting the following file:

```
select when regexp_contains(value, r'ABCDEF$') then 'ABCDEF'
```

Results in:

```
select
  when regexp_contains(value, r'ABCDEF) then 'ABCDEF') then 3512592308a6428d
```

The issue appears to be the $ in the regexp, as it works if you remove this.

**Comment by BenBirt** [comment]
dup of https://github.com/dataform-co/dataform-web-tracking/issues/247
